  export const siteData = {
    "Paradise Beach Flow Rate":{
      name:"Paradise Beach Flow Rate",
      "database":"WBLK_KOUG_FMU_BTU01",
      "field":"flowrate2",
      yAxisIndex:0,
    },
    "Paradise Beach Total Flow":{
      name:"Paradise Beach Total Flow",
      "database":"WBLK_KOUG_FMU_BTU01",
      "field":"flowtotal2",
       yAxisIndex:0,
    },
    "Paradise Beach St Francis Total Flow":{
      name:"Paradise Beach St Francis Total Flow",
      "database":"WBLK_KOUG_FMU_BTU01",
      "field":"flowrate1",
       yAxisIndex:0,
    },
    "Paradise Beach St Francis Flow Rate":{
      name:"Paradise Beach St Francis Flow Rate",
      "database":"WBLK_KOUG_FMU_BTU01",
      "field":"flowrate1",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 1 Total Flow":{
      name:"Hankey Sewage Pumpstation 1 Total Flow",
      "database":"NMBM_HANK_TOTAL_FLOW_TREND",
      "field":"hank_ps_g_total_flow_1",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 2 Total Flow":{
      name:"Hankey Sewage Pumpstation 2 Total Flow",
      "database":"NMBM_HANK_TOTAL_FLOW_TREND",
      "field":"hank_ps_g_total_flow_2",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation SUMP Level":{
      name:"Hankey Sewage Pumpstation SUMP Level",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_g_sump_level",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 1 Flow Rate":{
      name:"Hankey Sewage Pumpstation 1 Flow Rate",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_g_flow_rate_1",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 2 Flow Rate":{
      name:"Hankey Sewage Pumpstation 2 Flow Rate",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_g_flow_rate_2",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 1 Speed":{
      name:"Hankey Sewage Pumpstation 1 Speed",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_g_flow_rate_2",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 2 Speed":{
      name:"Hankey Sewage Pumpstation 2 Speed",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_p2_speed",
       yAxisIndex:0,
    },
    "Hankey Sewage Pumpstation 3 Speed":{
      name:"Hankey Sewage Pumpstation 3 Speed",
      "database":"HANK_FLOW_TREND",
      "field":"hank_ps_p3_speed",
       yAxisIndex:0,
    },"Glendinningvale Pump 1 Run Time":{
      name:"Glendinningvale Pump 1 Run Time",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_P1_rtm",
       yAxisIndex:0,
    },
    "Glendinningvale Pump 2 Run Time":{
      name:"Glendinningvale Pump 2 Run Time",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_P2_rtm",
       yAxisIndex:0,
    },
    "Glendinningvale Pump 1 Number Of Starts":{
      name:"Glendinningvale Pump 1 Number Of Starts",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_P1_stn",
       yAxisIndex:0,
    },
    "Glendinningvale Pump 2 Number Of Starts":{
      name:"Glendinningvale Pump 2 Number Of Starts",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_P2_stn",
       yAxisIndex:0,
    },
    "Glendinningvale Potential of Hydrogen":{
      name:"Glendinningvale Potential of Hydrogen",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_FTP_WTW_ph",
       yAxisIndex:0,
    },
    "Glendinningvale Oxidation Reduction Potential":{
      name:"Glendinningvale Oxidation Reduction Potential",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_FTP_WTW_orp",
       yAxisIndex:0,
    },
    "Glendinningvale Inlet Flow Rate":{
      name:"Glendinningvale Inlet Flow Rate",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_FTP_WTW_Inlet_Flow_Rate",
       yAxisIndex:0,
    },
    "Glendinningvale Inlet Total Flow":{
      name:"Glendinningvale Inlet Total Flow",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_Inlet_Total_Flow",
       yAxisIndex:0,
    },
    "Glendinningvale Inlet Pressure":{
      name:"Glendinningvale Inlet Pressure",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_FTP_WTW_Inlet_bar",
       yAxisIndex:0,
    },
    "Glendinningvale Borehole Flow Rate":{
      name:"Glendinningvale Borehole Flow Rate",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_FTP_WTW_borehole_Flow_Rate",
       yAxisIndex:0,
    },
    "Glendinningvale Borehole Total Flow":{
      name:"Glendinningvale Borehole Total Flow",
      "database":"NMBM_GLEN_TF_trend",
      "field":"glen_FTP_WTW_borehole_Total_Flow",
       yAxisIndex:0,
    },
    "Glendinningvale Reservoir Level":{
      name:"Glendinningvale Reservoir Level",
      "database":"NMBM_GLEN_Flow_trend",
      "field":"glen_r_res_lvl",
       yAxisIndex:0,
    },"Kareedouw K1 Total Flow":{
      name:"Kareedouw K1 Total Flow",
      "database":"KARK_K1_TOTAL_FLOW",
      "field":"gw_kark_k1_total_flow",
       yAxisIndex:0,
    },
    "Kareedouw K1 Flow Rate":{
      name:"Kareedouw K1 Flow Rate",
      "database":"KARK_K1_FLOW_RATE",
      "field":"gw_kark_k1_flow_rate",
       yAxisIndex:0,
    },
    "Kareedouw K1 Current":{
      name:"Kareedouw K1 Current",
      "database":"KARK_K1_FLOW_RATE",
      "field":"gw_kark_k1_current",
       yAxisIndex:0,
    },
    "Kareedouw K1 Level":{
      name:"Kareedouw K1 Level",
      "field":"gw_kark_k1_level",
      "database":"KARK_K1_FLOW_RATE",
       yAxisIndex:0,
    },
    "Kareedouw K2 Total Flow":{
      name:"Kareedouw K2 Total Flow",
      "field":"gw_kark_k2_total_flow",
      "database":"KARK_K2_TOTAL_FLOW",
       yAxisIndex:0,
    },
    "Kareedouw K2 Flow Rate":{
      name:"Kareedouw K2 Flow Rate",
      "field":"gw_kark_k2_flow_rate",
      "database":"KARK_K2_FLOW_RATE",
       yAxisIndex:0,
    },
    "Kareedouw K2 Current":{
      name:"Kareedouw K2 Current",
      "field":"gw_kark_k2_current",
      "database":"KARK_K2_FLOW_RATE",
       yAxisIndex:0,
    },
    "Kareedouw K2 Level":{
      name:"Kareedouw K2 Level",
      "field":"gw_kark_k2_level",
      "database":"KARK_K2_FLOW_RATE",
       yAxisIndex:0,
    },
    "Greenbushes Reservoir Level":{
      name:"Greenbushes Reservoir",
      "field":"level",
      "database":"BR_GB_RES_LVL",
       yAxisIndex:0,
    },
    "Greenbushes Flow Rate":{
      name:"Greenbushes Flow Rate",
      "field":"gb_R_FR",
      "database":"BR_GB_RES_LVL",
       yAxisIndex:0,
    },
    "Elandsjagt Flow Rate":{
      name:"Elandsjagt Flow Rate",
      "field":"wtw_elands_FR",
      "database":"WTW_ELANDS_TREND",
       yAxisIndex:0,
    },
    "Elandsjagt Pressure":{
      name:"Elandsjagt Pressure",
      "field":"wtw_elands_P",
      "database":"WTW_ELANDS_TREND",
       yAxisIndex:0,
    },"Emerald Hill Reservoir Level":{
      name:"Emerald Hill Reservoir Level",
      "field":"level",
      "database":"NMB_EMER_H_RES_LVL",
       yAxisIndex:0,
    },
    "Emerald Hill Flow Rate":{
      name:"Emerald Hill Flow Rate",
      "field":"emer_flow_rate",
      "database":"NMB_EMER_H_RES_LVL",
       yAxisIndex:0,
    },
    "Emerald Hill Total Flow":{
      name:"Emerald Hill Total Flow",
      "field":"emer_total_flow",
      "database":"NMB_EMER_H_TOTAL_RES_LVL",
       yAxisIndex:0,
    },
    "Airport Reservoir Level":{
      name:"Airport Reservoir Level",
      "field":"level1",
      "database":"WBLK_AIRP_RES_BTU01",
       yAxisIndex:0,
    },
    "Lee Samuals Drive Pressure":{
      name:"Lee Samuals Drive Pressure",
      "field":"pressure1",
      "database":"WDNR_LSAM_DMA_FLM01",
       yAxisIndex:0,
    },
    "Lee Samuals Drive Total Flow":{
      name:"Lee Samuals Drive Total Flow",
      "field":"totaliser1",
      "database":"WDNR_LSAM_DMA_FLM01",
       yAxisIndex:0,
    },
    "Lee Samuals Drive Flow Rate":{
      name:"Lee Samuals Drive Flow Rate",
      "field":"flowrate1",
      "database":"WDNR_LSAM_DMA_FLM01",
       yAxisIndex:0,
    },
    "McNoughton Township South Pressure":{
      name:"McNoughton Township South Pressure",
      "field":"pressure1",
      "database":"WDNR_MCNA_DMA_FLM01",
       yAxisIndex:0,
    },
    "McNoughton Township South Total Flow":{
      name:"McNoughton Township South Total Flow",
      "field":"totaliser1",
      "database":"WDNR_MCNA_DMA_FLM01",
       yAxisIndex:0,
    },
    "McNoughton Township South Flow Rate":{
      name:"McNoughton Township South Flow Rate",
      "field":"flowrate1",
      "database":"WDNR_MCNA_DMA_FLM01",
       yAxisIndex:0,
    },
    "Driftsands Reservoir Level":{
      name:"Driftsands Reservoir Level",
      "field":"drift_r_reservoir_level",
      "database":"NMB_DRIFT_RES_LVL",
       yAxisIndex:0,
    },
    "Driftsands Flow Rate 1":{
      name:"Driftsands Flow Rate 1",
      "field":"drift_r_flow_rate_1",
      "database":"NMB_DRIFT_RES_LVL",
       yAxisIndex:0,
    },"Driftsands Flow Rate 2":{
      name:"Driftsands Flow Rate 2",
      "field":"drift_r_flow_rate_2",
      "database":"NMB_DRIFT_RES_LVL",
       yAxisIndex:0,
    },
    "Driftsands Total Flow 1":{
      name:"Driftsands Total Flow 1",
      "field":"drift_r_total_flow_1",
      "database":"NMB_DRIFT_TOTAL_FLOW",
       yAxisIndex:0, 
    },
    "Driftsands Total Flow 2":{
      name:"Driftsands Total Flow 2",
      "field":"drift_r_total_flow_2",
      "database":"NMB_DRIFT_TOTAL_FLOW",
       yAxisIndex:0,
    },
    "Bergendal Reservoir Level":{
      name:"Bergendal Reservoir Level",
      "field":"bergen_r_level",
      "database":"GRAAF_BERGEN_RES",
       yAxisIndex:0,
    },
    "Umasizakhe Reservoir Level":{
      name:"Umasizakhe Reservoir Level",
      "field":"uma_r_level",
      "database":"GRAAF_UMA_RES",
       yAxisIndex:0,
    },
    "Wolwas Reservoir Level":{
      name:"Wolwas Reservoir Level",
      "field":"wolwas_r_level",
      "database":"GRAAF_WOLWAS_RES",
       yAxisIndex:0,
    },
    "Kroonvale Reservoir Level":{
      name:"Kroonvale Reservoir Level",
      "field":"kroon_r_level",
      "database":"GRAAF_KROON_RES",
       yAxisIndex:0,
    },
    "Tin Roof Reservoir Level":{
      name:"Tin Roof Reservoir Level",
      "field":"level",
      "database":"TIN_GRAAF_RES_LVL",
       yAxisIndex:0,
    },
    "Damcamp Reservoir Level":{
      name:"Damcamp Reservoir Level",
      "field":"level",
      "database":"DAMP_GRAAF_RES_LVL",
       yAxisIndex:0,
    },
    "Holding Reservoir Level":{
      name:"Holding Reservoir Level",
      "field":"level",
      "database":"HOL_GRAAF_RES_LVL",
       yAxisIndex:0,
    },
    "Bushy Park Soccoman Flow Rate":{
      name:"Bushy Park Soccoman Flow Rate",
      "field":"bush_church_socco_fr",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },
    "Bushy Park Steel Flow Rate":{
      name:"Bushy Park Steel Flow Rate",
      "field":"bush_church_steel_fr",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },"Bushy Park Soccoman Pressure":{
      name:"Bushy Park Soccoman Pressure",
      "field":"bush_church_socco_bar",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },
    "Bushy Park Steel Pressure":{
      name:"Bushy Park Steel Pressure",
      "field":"bush_church_steel_bar",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
      
    },
    "Bushy Park Pumpstation Flow Rate":{
      name:"Bushy Park Pumpstation Flow Rate",
      "field":"bush_church_steel_bar",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },
    "Bushy Park Combined Borehole Flow Rate":{
      name:"Bushy Park Combined Borehole Flow Rate",
      "field":"bush_gw_comb_flow_rate",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },
    "Bushy Park Holding Tank Level":{
      name:"Bushy Park Holding Tank Level",
      "field":"bush_tank_lvl",
      "database":"NMB_BUSH_FlowRate",
       yAxisIndex:0,
    },
    "Bushy Park Combined Total Flow":{
      name:"Bushy Park Combined Total Flow",
      "field":"bush_gw_TF",
      "database":"NMB_BUSH_FR",
       yAxisIndex:0,
    },
    "Bushy Park Pumpstation Total Flow":{
      name:"Bushy Park Pumpstation Total Flow",
      "field":"bush_ps_TF",
      "database":"NMB_BUSH_FR",
       yAxisIndex:0,
    },
    "Bushy Park Steel Total Flow":{
      name:"Bushy Park Steel Total Flow",
      "field":"bush_church_steel_TF",
      "database":"NMB_BUSH_FR",
       yAxisIndex:0,
    },
    "Bushy Park Soccoman Total Flow":{
      name:"Bushy Park Soccoman Total Flow",
      "field":"bush_church_soco_TF",
      "database":"NMB_BUSH_FR",
       yAxisIndex:0,
    },
    "Humansdorp Off Take Total Flow":{
      name:"Humansdorp Off Take Total Flow",
      "field":"flowtotal1",
      "database":"WBLK_KOUG_FMU_BTU04",
       yAxisIndex:0,
    },
    "Humansdorp Off Take Pressure":{
      name:"Humansdorp Off Take Pressure",
      "field":"pressure1",
      "database":"WBLK_KOUG_FMU_BTU04",
       yAxisIndex:0,
      
    },
    "Humansdorp Off Take Battery Level":{
      name:"Humansdorp Off Take Battery Level",
      "field":"battery_status",
      "database":"WBLK_KOUG_FMU_BTU04",
       yAxisIndex:0,
    },"Jeffreys Bay Off Take Total Flow":{
      name:"Jeffreys Bay Off Take Total Flow",
      "field":"flowtotal1",
      "database":"WBLK_KOUG_FMU_BTU05",
       yAxisIndex:0,
    },
    "Jeffreys Bay Off Take Battery Level":{
      name:"Jeffreys Bay Off Take Battery Level",
      "field":"flowrate1",
      "database":"WBLK_KOUG_FMU_BTU05",
       yAxisIndex:0,
    },
    "Kouga Main Line Pressure":{
      name:"Kouga Main Line Pressure",
      "field":"kou_main_line_pressure",
      "database":"KOU_MAIN_LINE",
       yAxisIndex:0,
    },
    "Kouga Main Line Battery Level":{
      name:"Kouga Main Line Battery Level",
      "field":"battery_status",
      "database":"WBLK_KOUG_FMU_BTU02",
       yAxisIndex:0,
    },
    "Ons Paradys Total Flow":{
      name:"Ons Paradys Total Flow",
      "field":"ons_para_TF",
      "database":"ONS_PARA_TOTAL_FLOW",
       yAxisIndex:0,
    },
    "Ons Paradys Battery Level":{
      name:"Ons Paradys Battery Level",
      "field":"ons_para_battery_level",
      "database":"ONS_PARA_BATTERY",
       yAxisIndex:0,
    },
    "St Francis Offtake Total Flow":{
      name:"St Francis Offtake Total Flow",
      "field":"jb_ST_Francis_OffTake_Total_Flow",
      "database":"JB_PB_SFO_TOTAL_FLOW",
       yAxisIndex:0,
    },

    "Gamtoos Break Water Pressure":{
      name:"Gamtoos Break Water Pressure",
      "field":"gbw_actual_pressure",
      "database":"NMNM_GWB_BAR_FLOW",
       yAxisIndex:0,
    },
    "Gamtoos Break Water Flow Rate":{
      name:"Gamtoos Break Water Flow Rate",
      "field":"gbw_flow_rate",
      "database":"NMNM_GWB_BAR_FLOW",
       yAxisIndex:0,
    },
    "Coega Kop Reservoir Pressure":{
      name:"Coega Kop Reservoir Pressure",
      "field":"pressure",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
    },
    "Olifantskop Reservoir Level":{
      name:"Olifantskop Reservoir Level",
      "field":"level1",
      "database":"WBLK_OLIF_RES_BTU01",
       yAxisIndex:0,
      
    },
    "Coega Kop to Coega IDZ Flow Rate":{
      name:"Coega Kop to Coega IDZ Flow Rate",
      "field":"nmb_cgk_r_coega_idz_outlet_flow_rate",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
      
    },
    "Coega Kop to Motherwell Total Flow":{
      name:"Coega Kop to Motherwell Total Flow",
      "field":"motherwelltotalflow",
      "database":"NMBM_CGK_R_TotalFlow",
       yAxisIndex:0,
    },
    "Coega Kop from Grassridge Total Flow":{
      name:"Coega Kop from Grassridge Total Flow",
      "field":"grassridgetotalflow",
      "database":"NMBM_CGK_R_TotalFlow",
       yAxisIndex:0,
    },
    "Coega Kop to Coega IDZ Total Flow":{
      name:"Coega Kop to Coega IDZ Total Flow",
      "field":"coegatotalflow",
      "database":"NMBM_CGK_R_TotalFlow",
       yAxisIndex:0,
    },
    "Coega Kop Inlet Chamber 2 Ml":{
      name:"Coega Kop Inlet Chamber 2 Ml",
      "field":"level",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
    },
    "Coega Kop North Chamber 17 Ml":{
      name:"Coega Kop North Chamber 17 Ml",
      "field":"coe_kop_cloud_r_level",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
    },
    "Coega Kop to Motherwell Flow Rate":{
      name:"Coega Kop to Motherwell Flow Rate",
      "field":"nmb_cgk_r_motherwell_outlet_flow_rate",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
    },
    "Coega Kop from Grassridge Flow Rate":{
      name:"Coega Kop from Grassridge Flow Rate",
      "field":"nmb_cgk_r_grassridge_inlet_flow_rate",
      "database":"NMBM_CGK_R_Trend",
       yAxisIndex:0,
    },
    "Chelsea Reservoir East Chamber Level":{
      name:"Chelsea Reservoir East Chamber Level",
      "field":"eastChamber",
      "database":"BR_CHE_RES_LVL",
       yAxisIndex:0,
    },
    "Chelsea Reservoir West Chamber Level":{
      name:"Chelsea Reservoir West Chamber Level",
      "field":"westChamber",
      "database":"BR_CHE_RES_LVL",
       yAxisIndex:0,
    },
    "Chelsea Reservoir Summit 1200 mm Flow Rate":{
      name:"Chelsea Reservoir Summit 1200 mm Flow Rate",
      "field":"che_r_fr1100",
      "database":"BR_CHE_RES_LVL",
       yAxisIndex:0,
    },
    "Chelsea Reservoir Greenbushes 600 mm Flow Rate":{
      name:"Chelsea Reservoir Greenbushes 600 mm Flow Rate",
      "field":"che_r_fr600",
      "database":"BR_CHE_RES_LVL",
       yAxisIndex:0,
    },"Chelsea Reservoir Summit 1200 mm Total Flow":{
      name:"Chelsea Reservoir Summit 1200 mm Total Flow",
      "field":"che_r_tf1100",
      "database":"CHEL_RES_TF",
       yAxisIndex:0,
    },
    "Chelsea Reservoir Greenbushes 600 mm Total Flow":{
      name:"Chelsea Reservoir Greenbushes 600 mm Total Flow",
      "field":"che_r_tf600",
      "database":"CHEL_RES_TF",
       yAxisIndex:0,
    },
    "Chatty Flow Rate":{
      name:"Chatty Flow Rate",
      "field":"flowRate",
      "database":"DRN_CHT_RES_TF",
       yAxisIndex:0,
    },
    "Grassridge East Chamber Level":{
      name:"Grassridge East Chamber Level",
      "field":"level",
      "database":"BR_GR_EC_RES_LVL",
       yAxisIndex:0,
    },
    "Grassridge West Chamber Level":{
      name:"Grassridge West Chamber Level",
      "field":"level",
      "database":"BR_GR_WC_RES_LVL",
       yAxisIndex:0,
    },
    "Van Stadens Reservoir Level":{
      name:"Van Stadens Reservoir Level",
      "field":"level",
      "database":"BR_VS_RES_LVL",
       yAxisIndex:0,
    },
    "Chatty North Chamber Level":{
      name:"Chatty North Chamber Level",
      "field":"level",
      "database":"DRN_CHT_NC_RES_LVL",
       yAxisIndex:0,
    },
    "Chatty Overhead Level":{
      name:"Chatty Overhead Level",
      "field":"level",
      "database":"DRN_CHT_OR_RES_LVL",
       yAxisIndex:0,
    },
    "Chatty South Chamber Level":{
      name:"Chatty South Chamber Level",
      "field":"level",
      "database":"DRN_CHT_SC_RES_LVL",
       yAxisIndex:0,
    },
    "Van Riebeeck Hoogte Delivery Level":{
      name:"Van Riebeeck Hoogte Delivery Level",
      "field":"level",
      "database":"DRN_VRH_DL_RES_LVL",
       yAxisIndex:0,
    },
    "Van Riebeeck Hoogte Suction Level":{
      name:"Van Riebeeck Hoogte Suction Level",
      "field":"level",
      "database":"DRN_VRH_SL_RES_LVL",
       yAxisIndex:0,
    },
    "Heatherbank Reservoir Level":{
      name:"Heatherbank Reservoir Level",
      "field":"level",
      "database":"DRS_HB_RES_LVL",
       yAxisIndex:0,
    },"Heatherbank Pump 1 Current":{
      name:"Heatherbank Pump 1 Current",
      "field":"hb_P1_CURRENT",
      "database":"DRS_HB_RES_LVL",
       yAxisIndex:0,
    },
    "Heatherbank Pump 2 Current":{
      name:"Heatherbank Pump 2 Current",
      "field":"hb_P2_CURRENT",
      "database":"DRS_HB_RES_LVL",
       yAxisIndex:0,
    },
    "Heatherbank Pump 3 Current":{
      name:"Heatherbank Pump 3 Current",
      "field":"hb_P3_CURRENT",
      "database":"DRS_HB_RES_LVL",
       yAxisIndex:0,
    },
    "Heatherbank Pump 1 Run Hours":{
      name:"Heatherbank Pump 1 Run Hours",
      "field":"hb_P1_RH",
      "database":"DRS_HB_PS_TF",
       yAxisIndex:0,
    },
    "Heatherbank Pump 2 Run Hours":{
      name:"Heatherbank Pump 2 Run Hours",
      "field":"hb_P2_RH",
      "database":"DRS_HB_PS_TF",
       yAxisIndex:0,
    },
    "Heatherbank Pump 3 Run Hours":{
      name:"Heatherbank Pump 3 Run Hours",
      "field":"hb_P3_RH",
      "database":"DRS_HB_PS_TF",
       yAxisIndex:0,
    },
    "Lovemore Heights Reservoir Level":{
      name:"Lovemore Heights Reservoir Level",
      "field":"lh_Res_lvl",
      "database":"DRS_LH_RES_LVL",
       yAxisIndex:0,
    },
    "Lovemore Heights Overhead Tank":{
      name:"Lovemore Heights Overhead Tank",
      "field":"level",
      "database":"DRS_LH_RES_LVL",
       yAxisIndex:0,
    },
    "Blue Horizon Bay Reservoir Level":{
      name:"Blue Horizon Bay Reservoir Level",
      "field":"level",
      "database":"DRS_BHB_RES_LVL",
       yAxisIndex:0,
    },
    "Theescombe Reservoir Level":{
      name:"Theescombe Reservoir Level",
      "field":"level",
      "database":"DRS_TC_RES_LVL",
       yAxisIndex:0,
    },
    "Rosedale Reservoir Level":{
      name:"Rosedale Reservoir Level",
      "field":"level",
      "database":"BR_RD_RES_LVL",
       yAxisIndex:0,
    },
    "Summit Reservoir Level":{
      name:"Summit Reservoir Level",
      "field":"level",
      "database":"BR_SM_TREND",
       yAxisIndex:0,
    },"Summit Flow Rate":{
      name:"Summit Flow Rate",
      "field":"flowRate",
      "database":"BR_SM_TREND",
       yAxisIndex:0,
    },
    "Grassridge Inlet Flow":{
      name:"Grassridge Inlet Flow",
      "field":"gr_R_INLET_FLOWS",
      "database":"GRASS_RIDGE_RES_FLOW_RATES",
       yAxisIndex:0,
    },
    "Grassridge Outlet Flow":{
      name:"Grassridge Outlet Flow",
      "field":"gr_R_OUTLET_FLOW",
      "database":"GRASS_RIDGE_RES_FLOW_RATES",
       yAxisIndex:0,
    },
    "Bethelsdorp Battery Level":{
      name:"Bethelsdorp Battery Level",
      "field":"battery_status",
      "database":"WDNR_BETH_FMU_BTU01",
       yAxisIndex:0,
    },
    "Bethelsdorp Total Flow":{
      name:"Bethelsdorp Total Flow",
      "field":"flowtotal1",
      "database":"WDNR_BETH_FMU_BTU01",
       yAxisIndex:0,
    },
    "Bethelsdorp Pressure":{
      name:"Bethelsdorp Pressure",
      "field":"pressure1",
      "database":"WDNR_BETH_FMU_BTU01",
       yAxisIndex:0,
    },
    "Bethelsdorp Flow Rate":{
      name:"Bethelsdorp Flow Rate",
      "field":"flowrate1",
      "database":"WDNR_BETH_FMU_BTU01",
       yAxisIndex:0,
    },
    "FM Tower Flow Rate":{
      name:"FM Tower Flow Rate",
      "field":"flowRate",
      "database":"FM_FMT_TREND",
       yAxisIndex:0,
    },
    "FM Tower Total Flow":{
      name:"FM Tower Total Flow",
      "field":"totalflow",
      "database":"FM_FMT_TF",
       yAxisIndex:0,
    },
    "FM Tower Pressure":{
      name:"FM Tower Pressure",
      "field":"pressure",
      "database":"FM_FMT_TREND",
       yAxisIndex:0,
    },
    "Coega IDZ Flow Rate":{
      name:"Coega IDZ Flow Rate",
      "field":"idz_FR",
      "database":"FPT_IDZT_FRs",
       yAxisIndex:0,
    },
    "Coega Motherwell Flow Rate":{
      name:"Coega Motherwell Flow Rate",
      "field":"motherwell_FR",
      "database":"FPT_IDZT_FRs",
       yAxisIndex:0,
    },"Gamtoos Bridge Steel Pipe Flow Rate":{
      name:"Gamtoos Bridge Steel Pipe Flow Rate",
      "field":"steel_pipe_FR",
      "database":"FPT_GT_BRG_TREND",
       yAxisIndex:0,
    },
    "Gamtoos Bridge Socoman Pipe Flow Rate":{
      name:"Gamtoos Bridge Socoman Pipe Flow Rate",
      "field":"socoman_pipe_FR",
      "database":"FPT_GT_BRG_TREND",
       yAxisIndex:0,
    },
    "Gamtoos Bridge Steel Pipe Pressure":{
      name:"Gamtoos Bridge Steel Pipe Pressure",
      "field":"steel_pipe_PRESS",
      "database":"FPT_GT_BRG_TREND",
       yAxisIndex:0,
    },
    "Gamtoos Bridge Socoman Pipe Pressure":{
      name:"Gamtoos Bridge Socoman Pipe Pressure",
      "field":"socoman_pipe_PRESS",
      "database":"FPT_GT_BRG_TREND",
       yAxisIndex:0,
    },
    "Uitenhage Flow Chamber Flow Rate":{
      name:"Uitenhage Flow Chamber Flow Rate",
      "field":"flow_rate",
      "database":"FPT_UIT_FC_TREND",
       yAxisIndex:0,
    },
    "Uitenhage Flow Chamber Pressure":{
      name:"Uitenhage Flow Chamber Pressure",
      "field":"pressure",
      "database":"FPT_UIT_FC_TREND",
       yAxisIndex:0,
    },
    "Humerail Borehol Level":{
      name:"Humerail Borehol Level",
      "field":"hum_gw_borehole_lvl",
      "database":"NMBM_HUM_GW_FLOWRATE",
       yAxisIndex:0,
    },
    "Humerail Raw Water Tank Level":{
      name:"Humerail Raw Water Tank Level",
      "field":"hum_gw_raw_water_tank_lvl",
      "database":"NMBM_HUM_GW_FLOWRATE",
       yAxisIndex:0,
    },
    "Humerail Final Water Tank Level":{
      name:"Humerail Final Water Tank Level",
      "field":"hum_gw_final_water_tank_lvl",
      "database":"NMBM_HUM_GW_FLOWRATE",
       yAxisIndex:0,
    },
    "Storms River Quarry Level":{
      name:"Storms River Quarry Level",
      "field":"ps_storms_quarry_level",
      "database":"STORMS_PS_TREND",
       yAxisIndex:0,
    },
    "Storms River Gorge Level":{
      name:"Storms River Gorge Level",
      "field":"ps_storms_gorge_level",
      "database":"STORMS_PS_TREND",
       yAxisIndex:0,
    },
    "Storms River Holding Reservoir Level":{
      name:"Storms River Holding Reservoir Level",
      "field":"wtw_storms_holding_reservoir_level",
      "database":"STORMS_WTW_TREND",
       yAxisIndex:0,
    },
    "Storms River Overhead Tank Level":{
      name:"Storms River Overhead Tank Level",
        "database":"STORMS_WTW_TREND",
        "field":"wtw_storms_overhead_tank_level",
         yAxisIndex:0,
      },
      "Crown Gardens Suction Pressure":{
        name:"Crown Gardens Suction Pressure",
        "database":"RW_CG_PS_TREND",
        "field":"common_suction_pressure",
         yAxisIndex:0,
      },
      "Crown Gardens Delivery Pressure":{
        name:"Crown Gardens Delivery Pressure",
        "database":"RW_CG_PS_TREND",
        "field":"common_delivery_pressure",
         yAxisIndex:0,
      },
      "Crown Gardens Sump Level":{
        name:"Crown Gardens Sump Level",
        "database":"RW_CG_PS_TREND",
        "field":"sump_level",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 1 Level":{
        name:"Crown Gardens Tower 1 Level",
        "database":"RW_CG_PS_TREND",
        "field":"tower1_level",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 1 Inlet Flow":{
        name:"Crown Gardens Tower 1 Inlet Flow",
        "database":"RW_CG_PS_TREND",
        "field":"tower1_inlet_flow",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 1 Outlet Flow":{
        name:"Crown Gardens Tower 1 Outlet Flow",
        "database":"RW_CG_PS_TREND",
        "field":"tower1_outlet_flow",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 2 Level":{
        name:"Crown Gardens Tower 2 Level",
        "field":"tower2_level",
        "database":"RW_CG_PS_TREND",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 2 Inlet Flow":{
        name:"Crown Gardens Tower 2 Inlet Flow",
        "field":"tower2_inlet_flow",
        "database":"RW_CG_PS_TREND",
         yAxisIndex:0,
      },
      "Crown Gardens Tower 2 Outlet Flow":{
        name:"Crown Gardens Tower 2 Outlet Flow",
        "field":"tower2_outlet_flow",
        "database":"RW_CG_PS_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Delivery Pressure":{
        name:"NMU Effluent Delivery Pressure",
        "field":"delivery_pressure",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Flow Rate":{
        name:"NMU Effluent Flow Rate",
        "field":"flowRate",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Dam Level":{
        name:"NMU Effluent Dam Level",
        "field":"dam_level",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Pump 1 Speed":{
        name:"NMU Effluent Pump 1 Speed",
        "field":"p1_speed",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Pump 2 Speed":{
        name:"NMU Effluent Pump 2 Speed",
        "field":"p2_speed",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Pump 3 Speed":{
        name:"NMU Effluent Pump 3 Speed",
        "field":"p3_speed",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "NMU Effluent Jockey Pump Speed":{
        name:"NMU Effluent Jockey Pump Speed",
        "field":"jp_speed",
        "database":"WW_PS_NMU_EFF_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 1 Actual Speed":{
        name:"Chelsea Pumpstation 1 Actual Speed",
        "field":"che_ps_pumpset_1_vsd_actual_speed",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 1 Delivery Pressure":{
        name:"Chelsea Pumpstation 1 Delivery Pressure",
        "field":"che_ps_pumpset_1_del_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 1 Suction Pressure":{
        name:"Chelsea Pumpstation 1 Suction Pressure",
        "field":"che_ps_pumpset_1_suct_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 2 Actual Speed":{
        name:"Chelsea Pumpstation 2 Actual Speed",
        "field":"che_ps_pumpset_2_vsd_actual_speed",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 2 Delivery Pressure":{
        name:"Chelsea Pumpstation 2 Delivery Pressure",
        "field":"che_ps_pumpset_2_del_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 2 Suction Pressure":{
        name:"Chelsea Pumpstation 2 Suction Pressure",
        "field":"che_ps_pumpset_2_suct_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 3 Actual Speed":{
        name:"Chelsea Pumpstation 3 Actual Speed",
        "field":"che_ps_pumpset_3_vsd_actual_speed",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 3 Delivery Pressure":{
        name:"Chelsea Pumpstation 3 Delivery Pressure",
        "field":"che_ps_pumpset_3_del_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      
      },
      "Chelsea Pumpstation 3 Suction Pressure":{
        name:"Chelsea Pumpstation 3 Suction Pressure",
        "field":"che_ps_pumpset_3_suct_pressure",
        "database":"CHELSEA_PS_TREND",
         yAxisIndex:0,
      },
      "Chelsea Pumpstation 4 Actual Speed":{
        name:"Chelsea Pumpstation 4 Actual Speed",
          "field":"che_ps_pumpset_4_vsd_actual_speed",
          "database":"CHELSEA_PS_TREND",
           yAxisIndex:0,
        },
        "Chelsea Pumpstation 4 Delivery Pressure":{
          name:"Chelsea Pumpstation 4 Delivery Pressure",
          "field":"che_ps_pumpset_4_del_pressure",
          "database":"CHELSEA_PS_TREND",
           yAxisIndex:0,
        },
        "Chelsea Pumpstation 4 Suction Pressure":{
          name:"Chelsea Pumpstation 4 Suction Pressure",
          "field":"che_ps_pumpset_4_suct_pressure",
          "database":"CHELSEA_PS_TREND",
           yAxisIndex:0,
      
        },
        "Chelsea Pumpstation 700 Flow Rate":{
          name:"Chelsea Pumpstation 700 Flow Rate",
          "field":"che_ps_700_flow_rate",
          "database":"CHELSEA_PS_TREND",
           yAxisIndex:0,
        },
        "Chelsea Pumpstation 700 Total Flow":{
          name:"Chelsea Pumpstation 700 Total Flow",
          "field":"che_ps_700_total_flow",
          "database":"CHEL_TF_TREND",
           yAxisIndex:0,
        },
        "Newton Park Pool Pressure":{
          name:"Newton Park Pool Pressure",
          "field":"delivery_pressure",
          "database":"delivery_pressure",
           yAxisIndex:0,
        },
        "Newton Park Pool Flow Rate":{
          name:"Newton Park Pool Flow Rate",
          "field":"flowRate",
          "database":"NMBM_NPP_GW_TREND",
           yAxisIndex:0,
        },
        "Newton Park Pool Water Level":{
          name:"Newton Park Pool Water Level",
          "field":"level",
          "database":"NMBM_NPP_GW_TREND",
           yAxisIndex:0,
        },
        "Newton Park Pool Total Flow":{
          name:"Newton Park Pool Total Flow",
          "field":"totalflow",
          "database":"NPP_TF_Trend",
           yAxisIndex:0,
        },
        "HD1 Water Level":{
          name:"HD1 Water Level",
          "field":"level_HD1",
          "database":"KLM_HUP_GW_TREND",
           yAxisIndex:0,
        },
        "HD1 Flow Rate":{
          name:"HD1 Flow Rate",
          "field":"flowRate_HD1",
          "database":"KLM_HUP_GW_TREND",
           yAxisIndex:0,
        },
        "HD1 Total Flow":{
          name:"HD1 Total Flow",
          "field":"total_flow_HD1",
          "database":"KLM_HUP_TF_TREND",
           yAxisIndex:0,
        },
        "HD2C Water Level":{
          name:"HD2C Water Level",
          "field":"level_HD2C",
          "database":"KLM_HUP2_GW_TREND",
           yAxisIndex:0,
        },
        "HD2C Flow Rate":{
          name:"HD2C Flow Rate",
          "field":"flowRate_HD2C",
          "database":"KLM_HUP2_GW_TREND",
           yAxisIndex:0,
        },
        "HD2C Total Flow":{
          name:"HD2C Total Flow",
          "field":"total_flow_HD2C",
          "database":"KLM_HUP2_TF_TREND",
           yAxisIndex:0,
        },
        "HD3 Water Level":{
          name:"HD3 Water Level",
          "field":"level_HD3",
          "database":"KLM_HUP3_GW_TREND",
           yAxisIndex:0,
        },
        "HD3 Flow Rate":{
          name:"HD3 Flow Rate",
          "field":"flowRate_HD3",
        "database":"KLM_HUP3_GW_TREND",
           yAxisIndex:0,
        },
        "HD3 Total Flow":{
          name:"HD3 Total Flow",
          "field":"total_flow_HD3",
          "database":"KLM_HUP3_TF_TREND",
           yAxisIndex:0,
        },
        "HD4 Water Level":{
          name:"HD4 Water Level",
          "field":"level_HD4",
          "database":"KLM_HUP4_GW_TREND",
           yAxisIndex:0,
        },
        "HD4 Flow Rate":{
          name:"HD4 Flow Rate",
          "field":"flowRate_HD4",
          "database":"KLM_HUP4_GW_TREND",
           yAxisIndex:0,
        },
        "HD4 Total Flow":{
          name:"HD4 Total Flow",
          "field":"total_flow_HD4",
          "database":"KLM_HUP4_TF_TREND",
           yAxisIndex:0,
        },
        "HD6 Water Level":{
          name:"HD6 Water Level",
          "field":"level_HD6",
      "database":"KLM_HUP6_GW_TREND",
           yAxisIndex:0,
        },
        "HD6 Flow Rate":{
          name:"HD6 Flow Rate",
          "field":"flowRate_HD6",
      "database":"KLM_HUP6_GW_TREND",
           yAxisIndex:0,
      
        },
        "HD6 Total Flow":{
          name:"HD6 Total Flow",
          "field":"total_flow_HD6",
      "database":"KLM_HUP6_TF_TREND",
           yAxisIndex:0,
        },
        "Stanford Road Delivery Pressure":{
          name:"Stanford Road Delivery Pressure",
          "field":"delivery_pressure",
      "database":"NMBM_STAN_BPS_TREND",
           yAxisIndex:0,
        },
        "Stanford Road Suction Pressure":{
          name:"Stanford Road Suction Pressure",
            "field":"suction_pressure",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Stanford Road Flow Rate":{
            name:"Stanford Road Flow Rate",
            "field":"flowRate",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Stanford Road Pump 1 Frequency":{
            name:"Stanford Road Pump 1 Frequency",
            "field":"p1_actfreq",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Stanford Road Pump 2 Frequency":{
            name:"Stanford Road Pump 2 Frequency",
            "field":"p2_actfreq",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Stanford Road Pump 3 Frequency":{
            name:"Stanford Road Pump 3 Frequency",
            "field":"p3_actfreq",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Stanford Road Pump 4 Frequency":{
            name:"Stanford Road Pump 4 Frequency",
            "field":"p4_actfreq",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Motherwell Delivery Pressure":{
            name:"Motherwell Delivery Pressure",
            "field":"p4_actfreq",
            "database":"NMBM_STAN_BPS_TREND",
             yAxisIndex:0,
          },
          "Motherwell Flow Rate":{
            name:"Motherwell Flow Rate",
            "field":"flowRate",
            "database":"NMBM_MW_PS_Trend",
             yAxisIndex:0,
          },
          "Motherwell Suction Pressure":{
            name:"Motherwell Suction Pressure",
            "field":"suction_pressure",
            "database":"NMBM_MW_PS_Trend",
             yAxisIndex:0,
          },
          "Motherwell Reservoir North Chamber Level":{
            name:"Motherwell Reservoir North Chamber Level",
            "field":"level",
            "database":"NMB_MW_RES_LVL",
             yAxisIndex:0,
          },
          "Motherwell Reservoir South Chamber Level":{
            name:"Motherwell Reservoir South Chamber Level",
            "field":"south_level",
            "database":"NMB_MW_RES_LVL",
             yAxisIndex:0,
          },
          "Motherwell Total Flow":{
            name:"Motherwell Total Flow",
            "field":"mw_g_p_tf",
            "database":"NMBM_MW_PS_Trend_TF",
             yAxisIndex:0,
          },
          "Motherwell Pump 1 Speed":{
            name:"Motherwell Pump 1 Speed",
              "field":"mw_p_p1_pump_speed",
              "database":"NMBM_MW_PS_Trend",
               yAxisIndex:0,
            },
            "Motherwell Pump 2 Speed":{
              name:"Motherwell Pump 2 Speed",
              "field":"mw_p_p2_pump_speed",
              "database":"NMBM_MW_PS_Trend",
               yAxisIndex:0,
            },
            "Motherwell Pump 3 Speed":{
              name:"Motherwell Pump 3 Speed",
              "field":"mw_p_p3_pump_speed",
              "database":"NMBM_MW_PS_Trend",
               yAxisIndex:0,
            },
            "Motherwell Pump 4 Speed":{
              name:"Motherwell Pump 4 Speed",
              "field":"mw_p_p4_pump_speed",
              "database":"NMBM_MW_PS_Trend",
               yAxisIndex:0,
            },
            "Nooitgedacht High Level Flow Rate":{
              name:"Nooitgedacht High Level Flow Rate",
              "field":"high_level_flow_rate",
              "database":"WTW_NGT_FM_TREND",
               yAxisIndex:0,
            },
            "Nooitgedacht Low Level Flow Rate":{
              name:"Nooitgedacht Low Level Flow Rate",
              "field":"low_level_flow_rate",
              "database":"WTW_NGT_FM_TREND",
               yAxisIndex:0,
      
            },
            "St Georges Borehole Flow Rate":{
              name:"St Georges Borehole Flow Rate",
              "field":"st_georges_wtw_gw_FR",
              "database":"WTW_ST_GEORGE_TREND",
               yAxisIndex:0,
            },
            "St Georges Borehole Total Flow":{
              name:"St Georges Borehole Total Flow",
              "field":"st_georges_wtw_gw_TF",
              "database":"WTW_ST_GEORGE_TREND_TF",
               yAxisIndex:0,
            },
            "St Georges Emerald Hill Flow Rate":{
              name:"St Georges Emerald Hill Flow Rate",
                "field":"st_georges_wtw_emer_hill_FR",
                "database":"WTW_ST_GEORGE_TREND",
                 yAxisIndex:0,
              },
              "St Georges Emerald Hill Total Flow":{
                name:"St Georges Emerald Hill Total Flow",
                  "field":"st_georges_wtw_emer_hill_TF",
                  "database":"WTW_ST_GEORGE_TREND_TF",
                   yAxisIndex:0,
                },
                "Malabar Reservoir Level":{
                  name:"Malabar Reservoir Level",
                  "field":"mali_lvl",
                  "database":"NMBM_MALI_R_DB",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 12 Level":{
                  name:"Kruisfontein Borhole 12 Level",
                  "field":"gw_klm_kruis12_lvl",
                  "database":"KLM_KRUIS12_FLOW",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 12 Current":{
                  name:"Kruisfontein Borhole 12 Current",
                  "field":"gw_klm_kruis12_current",
                  "database":"KLM_KRUIS12_FLOW",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 12 Pressure":{
                  name:"Kruisfontein Borhole 12 Pressure",
                  "field":"gw_klm_kruis12_bar",
                  "database":"KLM_KRUIS12_FLOW",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 12 Flow Rate":{
                  name:"Kruisfontein Borhole 12 Flow Rate",
                  "field":"gw_klm_kruis12_flow_rate",
                  "database":"KLM_KRUIS12_FLOW",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 12 Total Flow":{
                  name:"Kruisfontein Borhole 12 Total Flow",
                  "field":"gw_klm_kruis12_TF",
                  "database":"KLM_KRUIS12_TF",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 13 Level":{
                  name:"Kruisfontein Borhole 13 Level",
                  "field":"gw_klm_kruis13_lvl",
                  "database":"KLM_KRUIS13_FLOW",
                   yAxisIndex:0,
                },
                "Kruisfontein Borhole 13 Current":{
                  name:"Kruisfontein Borhole 13 Current",
                    "field":"gw_klm_kruis13_current",
                    "database":"KLM_KRUIS13_FLOW",
                     yAxisIndex:0,
                  },
                  "Kruisfontein Borhole 13 Pressure":{
                    name:"Kruisfontein Borhole 13 Pressure",
                      "field":"gw_klm_kruis13_bar",
                      "database":"KLM_KRUIS13_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 13 Flow Rate":{
                      name:"Kruisfontein Borhole 13 Flow Rate",
                      "field":"gw_klm_kruis13_flow_rate",
                      "database":"KLM_KRUIS13_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 13 Total Flow":{
                      name:"Kruisfontein Borhole 13 Total Flow",
                      "field":"gw_klm_kruis13_TF",
                      "database":"KLM_KRUIS13_TF",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 14 Level":{
                      name:"Kruisfontein Borhole 14 Level",
                      "field":"gw_klm_kruis14_lvl",
                      "database":"KLM_KRUIS14_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 14 Current":{
                      name:"Kruisfontein Borhole 14 Current",
                      "field":"gw_klm_kruis14_current",
                      "database":"KLM_KRUIS14_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 14 Pressure":{
                      name:"Kruisfontein Borhole 14 Pressure",
                      "field":"gw_klm_kruis14_bar",
                      "database":"KLM_KRUIS14_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 14 Flow Rate":{
                      name:"Kruisfontein Borhole 14 Flow Rate",
                      "field":"gw_klm_kruis14_flow_rate",
                      "database":"KLM_KRUIS14_FLOW",
                       yAxisIndex:0,
                    },
                    "Kruisfontein Borhole 14 Total Flow":{
                      name:"Kruisfontein Borhole 14 Total Flow",
                      "field":"gw_klm_kruis14_TF",
                      "database":"KLM_KRUIS14_TF",
                       yAxisIndex:0,
                    },
                    "Humansdorp Inlet Flow Rate":{
                      name:"Humansdorp Inlet Flow Rate",
                        "field":"klm_hup_wtw_FR",
                        "database":"WTW_HUMANSDORP_FLOW",
                         yAxisIndex:0,
                      },
                      "Humansdorp Inlet Total Flow":{
                        name:"Humansdorp Inlet Total Flow",
                          "field":"klm_hup_wtw_TF",
                          "database":"Humansdrop_wtw_tf",
                           yAxisIndex:0,
                        },
                        "Kruisfontein Reservoir Level":{
                          name:"Kruisfontein Reservoir Level",
                          "field":"level",
                          "database":"KLM_KRUIS_RES_LVL",
                           yAxisIndex:0,
                        },
                        "Kwanobuhle Reservoir Level":{
                          name:"Kwanobuhle Reservoir Level",
                          "field":"kwano_r_reservoir_level",
                          "database":"NMB_KWANO_R",
                           yAxisIndex:0,
                        },
                        "Kwanobuhle Reservoir Flow Rate 1":{
                          name:"Kwanobuhle Reservoir Flow Rate 1",
                          "field":"kwano_r_flow_rate_1",
                          "database":"NMB_KWANO_R",
                           yAxisIndex:0,
                        },
                        "Kwanobuhle Reservoir Flow Rate 2":{
                          name:"Kwanobuhle Reservoir Flow Rate 2",
                          "field":"kwano_r_flow_rate_2",
                          "database":"NMB_KWANO_R",
                           yAxisIndex:0,
                        },
                        "Kwanobuhle Reservoir Total Flow 1":{
                          name:"Kwanobuhle Reservoir Total Flow 1",
                          "field":"kwano_r_total_flow_1",
                          "database":"NMB_KWANO_R_TF",
                           yAxisIndex:0,
                        },
                        "Kwanobuhle Reservoir Total Flow 2":{
                          name:"Kwanobuhle Reservoir Total Flow 2",
                          "field":"kwano_r_total_flow_2",
                          "database":"NMB_KWANO_R_TF",
                           yAxisIndex:0,
                        },
                        "Isuzu Oven 1 VSD Speed":{
                          name:"Isuzu Oven 1 VSD Speed",
                          "field":"isuzu_oven1_vsd_speed",
                          "database":"ISUZU_TREND",
                           yAxisIndex:0,
                        },
                        "Isuzu Oven 1 Heat Exchanger Temperature":{
                          name:"Isuzu Oven 1 Heat Exchanger Temperature",
                            "field":"isuzu_oven1_heat_ecvh_temp",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 1 Temperature 1":{
                            name:"Isuzu Oven 1 Temperature 1",
                            "field":"isuzu_oven1_temp1",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 1 Temperature 2":{
                            name:"Isuzu Oven 1 Temperature 2",
                            "field":"isuzu_oven1_temp2",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 2 VSD Speed":{
                            name:"Isuzu Oven 2 VSD Speed",
                            "field":"isuzu_oven2_vsd_speed",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 2 Heat Exchanger Temperature":{
                            name:"Isuzu Oven 2 Heat Exchanger Temperature",
                            "field":"isuzu_oven2_heat_ecvh_temp",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 2 Temperature 1":{
                            name:"Isuzu Oven 2 Temperature 1",
                            "field":"isuzu_oven2_temp1",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Isuzu Oven 2 Temperature 2":{
                            name:"Isuzu Oven 2 Temperature 2",
                            "field":"isuzu_oven2_temp2",
                            "database":"ISUZU_TREND",
                             yAxisIndex:0,
                          },
                          "Rosedale Reservoir Total Flow":{
                            name:"Rosedale Reservoir Total Flow",
                            "field":"totaliser1",
                            "database":"WDNR_ROSE_RES_OUT01",
                             yAxisIndex:0,
                          },
                          "Rosedale Reservoir Flow Rate":{
                            name:"Rosedale Reservoir Flow Rate",
                            "field":"flowrate1",
                            "database":"WDNR_ROSE_RES_OUT01",
                             yAxisIndex:0,
                          },
                          "Rowallan Park Extension Pressure":{
                            name:"Rowallan Park Extension Pressure",
                            "field":"pressure1",
                            "database":"WDSR_ROWP_DMA_FLM01",
                             yAxisIndex:0,
                          },
                          "Rowallan Park Extension Total Flow":{
                            name:"Rowallan Park Extension Total Flow",
                            "field":"totaliser1",
                            "database":"WDSR_ROWP_DMA_FLM01",
                             yAxisIndex:0,
                          },
                          "Rowallan Park Extension Flow Rate":{
                            name:"Rowallan Park Extension Flow Rate",
                            "field":"flowrate1",
                            "database":"WDSR_ROWP_DMA_FLM01",
                             yAxisIndex:0,
                          },
                          "Linton Back Wash Flow Rate":{
                            name:"Linton Back Wash Flow Rate",
                            "field":"lin_wtw_back_wash_FR",
                            "database":"NMBM_LIN_FLOW",
                             yAxisIndex:0,
                          },
                          "Linton Back Wash Total Flow":{
                            name:"Linton Back Wash Total Flow",
                            "field":"lin_wtw_back_wash_TF",
                            "database":"NMBM_LIN_TF",
                             yAxisIndex:0,
                          },
                          "Linton Raw Water Flow Rate":{
                            name:"Linton Raw Water Flow Rate",
                            "field":"lin_wtw_raw_water_FR",
                            "database":"NMBM_LIN_FLOW",
                             yAxisIndex:0,
      
                          }, "Linton Raw Water Total Flow":{
                            name:"Linton Raw Water Total Flow",
                            "field":"lin_wtw_raw_water_TF",
                            "database":"NMBM_LIN_TF",
                             yAxisIndex:0,
                          },
                          "Linton Final Water Flow Rate":{
                            name:"Linton Final Water Flow Rate",
                            "field":"lin_wtw_final_water_fr",
                            "database":"NMBM_LIN_FLOW",
                             yAxisIndex:0,
                          },
                          "Linton Final Water Total Flow":{
                            name:"Linton Final Water Total Flow",
                            "field":"lin_wtw_final_water_tf",
                            "database":"NMBM_LIN_TF",
                             yAxisIndex:0,
                          },
                          "Linton Reservoir Level":{
                            name:"Linton Reservoir Level",
                            "field":"level",
                            "database":"LIN_R_LVL",
                             yAxisIndex:0,
                          },
                        }