

export interface Dates {
  startDate: string;
  endDate: string;
}

export interface Sites {
  sites: any[];
  startDate: string;
  endDate: string;
}

export interface PeriodicElement {
  name: string;
  min: number;
  max: number;
  average: number;
}
export const trendArray = [

  "LSD_FLOW_RATE_arr",
"LSD_TOTAL_FLOW_arr",
"LSD_PRESSURE_arr",
"McNougTown_FLOW_RATE_arr",
"McNougTown_TOTAL_FLOW_arr",
"McNougTown_PRESSURE_arr",

  "AIR_PRT_LVL_arr",

  "EMER_H_Level_arr",
  "KARK_K1_TF_arr",
  "KARK_K1_FR_arr",
  "KARK_K1_CUR_arr",
  "KARK_K1_LVL_arr",
  "KARK_K2_TF_arr",
  "KARK_K2_FR_arr",
  "KARK_K2_CUR_arr",
  "KARK_K2_LVL_arr",
  "GBarray",
  "GBFRarray",
  "ELA_FR_arr",
  "ELA_P_arr",
  "NMB_SCHOE_PRESSURE_array",
  "NMB_SCHOE_RES_LEVEL_array",
  "NMB_SCHOE_ACTUATOR_POSITION_array",
  "NMB_SCHOE_ACTUATOR_SET_POINT_array",
  "drift_R_reservoir_level_arr",
  "drift_R_flow_rate_1_arr",
  "drift_R_flow_rate_2_arr",
  "drift_R_total_flow_1_arr",
  "drift_R_total_flow_2_arr",
  "nmb_schoe_r_actuator_valve_feedback_signal_error_arr",
  "nmb_schoe_r_actuator_valve_command_signal_error_arr",
  "nmb_schoe_r_reservoir_level_signal_error_arr",
  "nmb_schoe_r_actuator_valve_fault_arr",
  "nmb_schoe_r_actuator_valve_torque_fail_close_arr",
  "nmb_schoe_r_actuator_valve_torque_fail_open_arr",
  "nmb_schoe_r_general_fault_arr",
  "nmb_schoe_r_actuator_general_fault_arr",
  "nmb_schoe_r_actuator_valve_timeout_arr",
  "BERGEN_RES_R_LVL_arr",
  "WOLWAS_RES_R_LVL_arr",
  "UMI_RES_R_LVL_arr",
  "KROON_RES_R_LVL_arr",
  "TINROOF_LVL_RES_LVL_arr",
  "DAMCAMP_LVL_RES_LVL_arr",
  "HOLDING_LVL_RES_LVL_arr",
  "BUSH_CHURCH_SOCO_FR_arr",
  "BUSH_CHURCH_STEEL_FR_arr",
  "BUSH_CHURCH_SOCCO_BAR_arr",
  "BUSH_CHURCH_STEEL_BAR_arr",
  "BUSH_PUMP_FR_arr",
  "BUSH_GW_COMB_FLOW_RATE_arr",
  "BUSH_TANK_LVL_arr",
  "BUSH_GW_TF_arr",
  "BUSH_PUMP_TF_arr",
  "BUSH_STEEL_TF_arr",
  "BUSH_SOCO_TF_arr",
  "HUM_OFF_TAKE_TF_arr",
  "HUM_OFF_TAKE_BAR_arr",
  "HUM_OFF_TAKE_BAT_arr",
  "JEFF_OFF_TAKE_TF_arr",
  "JEFF_OFF_TAKE_BAT_arr",
  "KOU_MAIN_LINE_BAR_arr",
  "KOU_MAIN_LINE_BAT_arr",
  "ONS_PARA_TF_arr",
  "ONS_PARA_BAT_arr",
  "ST_FRAN_OFF_TF_arr",
  "PARA_BEA_TF_arr",
  "ST_FRAN_PARA_BEA_BAT_arr",
  "GBW_ACT_BAR_arr",
  "GBW_FLO_RAT_arr",
  "EMER_H_Flow_Rate_arr",
  "EMER_H_Total_Flow_arr",
  "CGK_PRESSURE_array",
  "OLI_LVL_array",
  "CGK_COEGA_FLOW_RATE_array",
  "CGK_MOTHERWELL_TOTAL_FLOW_array",
  "CGK_GRASSRIDGE_TOTAL_FLOW_array",
  "CGK_COEGA_TOTAL_FLOW_array",
  "CGK_LEVEL_array",
  "CGK_KOP_NC_17_ML_array",
  "CGK_MOTHERWELL_FLOW_RATE_array",
  "CGK_GRASSRIDGE_FLOW_RATE_array",
  "CHE_East_array",
  "CHE_West_array",
  "CHE_R_FR1200_arr",
  "CHE_R_FR600_arr",
  "CHE_R_TF1200_arr",
  "CHE_R_TF600_arr",

  "CHE_FlowRate_array",
  "GR_EC_array",
  "GR_WC_array",
  "VSarray",
  "CHT_NC_array",
  "CHT_OR_array",
  "CHT_SC_array",
  "VRH_DL_array",
  "VRH_SL_array",
  "HBarray",
  "hb_P1_CURRENT_arr",
  "hb_P2_CURRENT_arr",
  "hb_P3_CURRENT_arr",
  "hb_P1_RH_arr",
  "hb_P2_RH_arr",
  "hb_P3_RH_arr",
  "LHarray",
  "DRS_LH_RES_LVL_arr",
  "BHB_array",
  "TCarray",
  "RD_LVL_array",
  "SM_LVL_array",
  "SM_FR_array",
  "GR_R_INLET_Arr",
  "GR_R_OUTLET_Arr",
  "BETH_BATTERY_STATUS_array",
  "BETH_TOTAL_FLOW_array",
  "BETH_PRESS_array",
  "BETH_FLOW_RATE_array",
  "FMT_FR_array",
  "FMT_TF_array",
  "FMT_PRESS_array",
  "IDZ_FR_array",
  "IDZ_MW_FR_array",
  "GT_BRG_STL_FR_array",
  "GT_BRG_SOCO_FR_array",
  "GT_BRG_STL_PRESS_array",
  "GT_BRG_SOCO_PRESS_array",
  "UIT_FC_FR_array",
  "UIT_FC_PRESS_array",
  "HUM_GW_BOR_LVL_arr",
  "HUM_GW_RAW_WATER_TANK_LVL_arr",
  "HUM_GW_FIN_WAT_TANK_LVL_arr",
  "STORMS_QUARRY_LEVEL_Arr",
  "STORMS_GORGE_LEVEL_Arr",
  "STORMS_HOLDING_RESERVOIR_LEVEL_Arr",
  "STORMS_OVERHEAD_TANK_LEVEL_Arr",
  "CG_CSP_Arr",
  "CG_CDP_Arr",
  "CG_S_LVL_Arr",
  "CG_T1_LVL_Arr",
  "CG_T1_IF_Arr",
  "CG_T1_OF_Arr",
  "CG_T2_LVL_Arr",
  "CG_T2_IF_Arr",
  "CG_T2_OF_Arr",
  "NMU_EFF_DP_Arr",
  "NMU_EFF_FR_Arr",
  "NMU_EFF_DAM_LVL_Arr",
  "NMU_EFF_P1_SPEED_Arr",
  "NMU_EFF_P2_SPEED_Arr",
  "NMU_EFF_P3_SPEED_Arr",
  "NMU_EFF_JP_SPEED_Arr",
  "CHE_PS_P1_ACTUAL_SPEED_Arr",
  "CHE_PS_P1_DEL_PRESS_Arr",
  "CHE_PS_P1_SUCT_PRESS_Arr",
  "CHE_PS_P2_ACTUAL_SPEED_Arr",
  "CHE_PS_P2_DEL_PRESS_Arr",
  "CHE_PS_P2_SUCT_PRESS_Arr",
  "CHE_PS_P3_ACTUAL_SPEED_Arr",
  "CHE_PS_P3_DEL_PRESS_Arr",
  "CHE_PS_P3_SUCT_PRESS_Arr",
  "CHE_PS_P4_ACTUAL_SPEED_Arr",
  "CHE_PS_P4_DEL_PRESS_Arr",
  "CHE_PS_P4_SUCT_PRESS_Arr",
  "CHE_PS_700_FLOW_RATE_Arr",
  "CHE_PS_700_TOTAL_FLOW_Arr",
  "NMBM_NPP_GW_PRESSURE_Arr",
  "NMBM_NPP_GW_FLOW_RATE_Arr",
  "NMBM_NPP_GW_LEVEL_Arr",
  "NMBM_NPP_GW_TOTAL_FLOW_Arr",
  "KLM_HUP_WATER_LEVEL_Arr",
  "KLM_HUP_FLOWRATE_Arr",
  "KLM_HUP_TOTALFLOW_Arr",
  "KLM_HUP2_WATER_LEVEL_Arr",
  "KLM_HUP2_FLOWRATE_Arr",
  "KLM_HUP2_TOTALFLOW_Arr",
  "KLM_HUP3_WATER_LEVEL_Arr",
  "KLM_HUP3_FLOWRATE_Arr",
  "KLM_HUP3_TOTALFLOW_Arr",
  "KLM_HUP4_WATER_LEVEL_Arr",
  "KLM_HUP4_FLOWRATE_Arr",
  "KLM_HUP4_TOTALFLOW_Arr",
  "KLM_HUP6_WATER_LEVEL_Arr",
  "KLM_HUP6_FLOWRATE_Arr",
  "KLM_HUP6_TOTALFLOW_Arr",
  "STAN_BPS_DeliveryPressure_Arr",
  "STAN_BPS_SuctionPressure_Arr",
  "STAN_BPS_FlowRate_Arr",
  "STAN_BPS_P1_FREQ_Arr",
  "STAN_BPS_P2_FREQ_Arr",
  "STAN_BPS_P3_FREQ_Arr",
  "STAN_BPS_P4_FREQ_Arr",
  "MW_BPS_DeliveryPressure_Arr",
  "MW_BPS_FlowRate_Arr",
  "MW_BPS_SuctionPressure_Arr",
  "MW_NORTH_LVL_array",
  "MW_SOUTH_LVL_array",
  "MW_P_TF_arr",
  "MW_P1_PUMP_RPM_arr",
  "MW_P2_PUMP_RPM_arr",
  "MW_P3_PUMP_RPM_arr",
  "MW_P4_PUMP_RPM_arr",

  "WTW_NGT_FM_HIGH_FR_Arr",
  "WTW_NGT_FM_LOW_FR_Arr",
  "st_georges_wtw_gw_FR_arr",
"st_georges_wtw_gw_TF_arr",
"st_georges_wtw_emer_hill_FR_arr",
"st_georges_wtw_emer_hill_TF_arr",
"mala_lvl_arr",
"klm_kruis12_lvl_arr",
"klm_kruis12_current_arr",
"klm_kruis12_bar_arr",
"klm_kruis12_flow_rate_arr",
"klm_kruis12_total_flow_arr",
"klm_kruis13_lvl_arr",
"klm_kruis13_current_arr",
"klm_kruis13_bar_arr",
"klm_kruis13_flow_rate_arr",
"klm_kruis13_total_flow_arr",
"klm_kruis14_lvl_arr",
"klm_kruis14_current_arr",
"klm_kruis14_bar_arr",
"klm_kruis14_flow_rate_arr",
"klm_kruis14_total_flow_arr",
"klm_hup_wtw_flow_arr",
"klm_hup_wtw_tf_arr",
"klm_kruis_res_lvl_arr",
"KWANO_R_RES_LVL_arr",
"KWANO_R_FLOW_RATE_1_arr",
"KWANO_R_FLOW_RATE_2_arr",
"KWANO_R_TOTAL_FLOW_1_arr",
"KWANO_R_TOTAL_FLOW_2_arr",
"isuzu_oven1_vsd_speed_arr",
"isuzu_oven1_heat_ecvh_temp_arr",
"isuzu_oven1_temp1_arr",
"isuzu_oven1_temp2_arr",
"isuzu_oven2_vsd_speed_arr",
"isuzu_oven2_heat_ecvh_temp_arr",
"isuzu_oven2_temp1_arr",
"isuzu_oven2_temp2_arr",
"WDNR_ROSE_TF_arr",
"WDNR_ROSE_FR_arr",
"WDSR_ROWP_BAR_arr",
"WDSR_ROWP_TF_arr",
"WDSR_ROWP_FR_arr",

"lint_wtw_back_wash_FR_ARR",
"lint_wtw_back_wash_TF_ARR",
"lint_wtw_raw_water_FR_ARR",
"lint_wtw_raw_water_TF_ARR",
"lint_wtw_final_water_FR_ARR",
"lint_wtw_final_water_TF_ARR",
"lint_res_lvl_ARR",

"glen_r_res_lvl_arr",
"glen_FTP_WTW_Inlet_Flow_Rate_arr",
"glen_FTP_WTW_Inlet_Total_Flow_arr",
"glen_FTP_WTW_Inlet_bar_arr",
"glen_FTP_WTW_borehole_Flow_Rate_arr",
"glen_FTP_WTW_borehole_Total_Flow_arr",

"glen_FTP_WTW_P1_rtm_arr",
"glen_FTP_WTW_P2_rtm_arr",
"glen_FTP_WTW_P1_stn_arr",
"glen_FTP_WTW_P2_stn_arr",
"glen_FTP_WTW_ph_arr",
"glen_FTP_WTW_orp_arr",

"hank_ps_g_total_flow_1_arr",
"hank_ps_g_total_flow_2_arr",
"hank_ps_g_sump_level_arr",
"hank_ps_g_flow_rate_1_arr",
"hank_ps_g_flow_rate_2_arr",
"hank_ps_p1_speed_arr",
"hank_ps_p2_speed_arr",
"hank_ps_p3_speed_arr",

"para_flow_rate_arr",
"para_total_flow_arr",
"para_st_flow_rate_arr",
"para_st_total_flow_arr",
  ]


  //make this axis map a hash map
  export const siteVariableMap = {

    "Paradise Beach Flow Rate":"para_flow_rate_arr",
    "Paradise Beach Total Flow":"para_total_flow_arr",
    "Paradise Beach St Francis Total Flow":"para_st_flow_rate_arr",
    "Paradise Beach St Francis Flow Rate":"para_st_total_flow_arr",

    "Hankey Sewage Pumpstation 1 Total Flow":"hank_ps_g_total_flow_1_arr",
    "Hankey Sewage Pumpstation 2 Total Flow":"hank_ps_g_total_flow_2_arr",
    "Hankey Sewage Pumpstation SUMP Level":"hank_ps_g_sump_level_arr",
    "Hankey Sewage Pumpstation 1 Flow Rate":"hank_ps_g_flow_rate_1_arr",
    "Hankey Sewage Pumpstation 2 Flow Rate":"hank_ps_g_flow_rate_2_arr",
    "Hankey Sewage Pumpstation 1 Speed":"hank_ps_p1_speed_arr",
    "Hankey Sewage Pumpstation 2 Speed":"hank_ps_p2_speed_arr",
    "Hankey Sewage Pumpstation 3 Speed":"hank_ps_p3_speed_arr",



    "Glendinningvale Pump 1 Run Time":"glen_FTP_WTW_P1_rtm_arr",
    "Glendinningvale Pump 2 Run Time":"glen_FTP_WTW_P2_rtm_arr",
    "Glendinningvale Pump 1 Number Of Starts":"glen_FTP_WTW_P1_stn_arr",
    "Glendinningvale Pump 2 Number Of Starts":"glen_FTP_WTW_P2_stn_arr",
    "Glendinningvale Potential of Hydrogen":"glen_FTP_WTW_ph_arr",
    "Glendinningvale Oxidation Reduction Potential":"glen_FTP_WTW_orp_arr",

    "Glendinningvale Inlet Flow Rate":"glen_FTP_WTW_Inlet_Flow_Rate_arr",
    "Glendinningvale Inlet Total Flow":"glen_FTP_WTW_Inlet_Total_Flow_arr",
    "Glendinningvale Inlet Pressure":"glen_FTP_WTW_Inlet_bar_arr",
    "Glendinningvale Borehole Flow Rate":"glen_FTP_WTW_borehole_Flow_Rate_arr",
    "Glendinningvale Borehole Total Flow":"glen_FTP_WTW_borehole_Total_Flow_arr",
    "Glendinningvale Reservoir Level":"glen_r_res_lvl_arr",


    "Kareedouw K1 Total Flow":"KARK_K1_TF_arr",
    "Kareedouw K1 Flow Rate":"KARK_K1_FR_arr",
    "Kareedouw K1 Current":"KARK_K1_CUR_arr",
    "Kareedouw K1 Level":"KARK_K1_LVL_arr",
    "Kareedouw K2 Total Flow":"KARK_K2_TF_arr",
    "Kareedouw K2 Flow Rate":"KARK_K2_FR_arr",
    "Kareedouw K2 Current":"KARK_K2_CUR_arr",
    "Kareedouw K2 Level":"KARK_K2_LVL_arr",
    "Greenbushes Reservoir Level":"GBarray",
    "Greenbushes Flow Rate":"GBFRarray",
    "Elandsjagt Flow Rate":"ELA_FR_arr",
    "Elandsjagt Pressure":"ELA_P_arr",
    "Emerald Hill Reservoir Level":"EMER_H_Level_arr",
    "Emerald Hill Flow Rate" :"EMER_H_Flow_Rate_arr",
    "Emerald Hill Total Flow" :"EMER_H_Total_Flow_arr",
    "Airport Reservoir Level":"AIR_PRT_LVL_arr",
    "Lee Samuals Drive Pressure":"LSD_PRESSURE_arr",
    "Lee Samuals Drive Total Flow":"LSD_TOTAL_FLOW_arr",
    "Lee Samuals Drive Flow Rate":"LSD_FLOW_RATE_arr",
    "McNoughton Township South Pressure":"McNougTown_PRESSURE_arr",
    "McNoughton Township South Total Flow":"McNougTown_TOTAL_FLOW_arr",
    "McNoughton Township South Flow Rate":"McNougTown_FLOW_RATE_arr",
    "Schoemanshoek Pressure":"NMB_SCHOE_PRESSURE_array",
    "Schoemanshoek Level":"NMB_SCHOE_RES_LEVEL_array",
    "Schoemanshoek Actuator Position":"NMB_SCHOE_ACTUATOR_POSITION_array",
    "Schoemanshoek Actuator Set Point":"NMB_SCHOE_ACTUATOR_SET_POINT_array",
    "Driftsands Reservoir Level":"drift_R_reservoir_level_arr",
    "Driftsands Flow Rate 1" :"drift_R_flow_rate_1_arr",
    "Driftsands Flow Rate 2":"drift_R_flow_rate_2_arr",
    "Driftsands Total Flow 1":"drift_R_total_flow_1_arr",
    "Driftsands Total Flow 2":"drift_R_total_flow_2_arr",
    "Schoemanshoek Actuator Valve Feedback Signal":"nmb_schoe_r_actuator_valve_feedback_signal_error_arr",
    "Schoemanshoek Actuator Valve Command Signal":"nmb_schoe_r_actuator_valve_command_signal_error_arr",
    "Schoemanshoek Reservoir Level Signal Error":"nmb_schoe_r_reservoir_level_signal_error_arr",
    "Schoemanshoek Actuator Valve Fault":"nmb_schoe_r_actuator_valve_fault_arr",
    "Schoemanshoek Actuator Valve Torque Fail Close":"nmb_schoe_r_actuator_valve_torque_fail_close_arr",
    "Schoemanshoek Actuator Valve Torque Fail Open":"nmb_schoe_r_actuator_valve_torque_fail_open_arr",
    "Schoemanshoek General Fault":"nmb_schoe_r_general_fault_arr",
    "Schoemanshoek Actuator General Fault":"nmb_schoe_r_actuator_general_fault_arr",
    "Schoemanshoek Actuator Valve Timeout":"nmb_schoe_r_actuator_valve_timeout_arr",
    "Bergendal Reservoir Level":"BERGEN_RES_R_LVL_arr",
    "Umasizakhe Reservoir Level" :"WOLWAS_RES_R_LVL_arr",
    "Wolwas Reservoir Level":"UMI_RES_R_LVL_arr",
  "Kroonvale Reservoir Level"  :"KROON_RES_R_LVL_arr",
  "Tin Roof Reservoir Level"  :"TINROOF_LVL_RES_LVL_arr",
  "Damcamp Reservoir Level" :"DAMCAMP_LVL_RES_LVL_arr",
  "Holding Reservoir Level" :"HOLDING_LVL_RES_LVL_arr",
  "Bushy Park Soccoman Flow Rate":"BUSH_CHURCH_SOCO_FR_arr",
  "Bushy Park Steel Flow Rate":"BUSH_CHURCH_STEEL_FR_arr",
  "Bushy Park Soccoman Pressure":"BUSH_CHURCH_SOCCO_BAR_arr",
  "Bushy Park Steel Pressure":"BUSH_CHURCH_STEEL_BAR_arr",
  "Bushy Park Pumpstation Flow Rate":"BUSH_PUMP_FR_arr",
  "Bushy Park Combined Borehole Flow Rate":"BUSH_GW_COMB_FLOW_RATE_arr",
  "Bushy Park Holding Tank Level":"BUSH_TANK_LVL_arr",
  "Bushy Park Combined Total Flow":"BUSH_GW_TF_arr",
  "Bushy Park Pumpstation Total Flow":"BUSH_PUMP_TF_arr",
  "Bushy Park Steel Total Flow":"BUSH_STEEL_TF_arr",
  "Bushy Park Soccoman Total Flow":"BUSH_SOCO_TF_arr",
  "Humansdorp Off Take Total Flow"  :"HUM_OFF_TAKE_TF_arr",
  "Humansdorp Off Take Pressure" :"HUM_OFF_TAKE_BAR_arr",
  "Humansdorp Off Take Battery Level" :"HUM_OFF_TAKE_BAT_arr",
  "Jeffreys Bay Off Take Total Flow" :"JEFF_OFF_TAKE_TF_arr",
  "Jeffreys Bay Off Take Battery Level":"JEFF_OFF_TAKE_BAT_arr",
  "Kouga Main Line Pressure":"KOU_MAIN_LINE_BAR_arr",
  "Kouga Main Line Battery Level" :"KOU_MAIN_LINE_BAT_arr",
  "Ons Paradys Total Flow":"ONS_PARA_TF_arr",
  "Ons Paradys Battery Level":"ONS_PARA_BAT_arr",
  "St Francis Offtake Total Flow" :"ST_FRAN_OFF_TF_arr",
  "Paradise/St Francis Battery Level" :"ST_FRAN_PARA_BEA_BAT_arr",
  "Gamtoos Break Water Pressure" :"GBW_ACT_BAR_arr",
  "Gamtoos Break Water Flow Rate" :"GBW_FLO_RAT_arr",
  "Coega Kop Reservoir Pressure" :"CGK_PRESSURE_array",
  "Olifantskop Reservoir Level" :"OLI_LVL_array",
  "Coega Kop to Coega IDZ Flow Rate" :"CGK_COEGA_FLOW_RATE_array",
  "Coega Kop to Motherwell Total Flow":"CGK_MOTHERWELL_TOTAL_FLOW_array",
  "Coega Kop from Grassridge Total Flow" :"CGK_GRASSRIDGE_TOTAL_FLOW_array",
  "Coega Kop to Coega IDZ Total Flow" :"CGK_COEGA_TOTAL_FLOW_array",
  "Coega Kop Inlet Chamber 2 Ml"  :"CGK_LEVEL_array",
  "Coega Kop North Chamber 17 Ml":"CGK_KOP_NC_17_ML_array",
  "Coega Kop to Motherwell Flow Rate":"CGK_MOTHERWELL_FLOW_RATE_array",
  "Coega Kop from Grassridge Flow Rate":"CGK_GRASSRIDGE_FLOW_RATE_array",
  "Chelsea Reservoir East Chamber Level":"CHE_East_array",
  "Chelsea Reservoir West Chamber Level":"CHE_West_array",
  "Chelsea Reservoir Summit 1200 mm Flow Rate":"CHE_R_FR1200_arr",
  "Chelsea Reservoir Greenbushes 600 mm Flow Rate":"CHE_R_FR600_arr",
  "Chelsea Reservoir Summit 1200 mm Total Flow":"CHE_R_TF1200_arr",
  "Chelsea Reservoir Greenbushes 600 mm Total Flow":"CHE_R_TF600_arr",
  "Chatty Flow Rate" :"CHE_FlowRate_array",
  "Grassridge East Chamber Level" :"GR_EC_array",
  "Grassridge West Chamber Level":"GR_WC_array",
  "Van Stadens Reservoir Level":"VSarray",
  "Chatty North Chamber Level":"CHT_NC_array",
  "Chatty Overhead Level":"CHT_OR_array",
  "Chatty South Chamber Level":"CHT_SC_array",
  "Van Riebeeck Hoogte Delivery Level":"VRH_DL_array",
  "Van Riebeeck Hoogte Suction Level":"VRH_SL_array",
  "Heatherbank Reservoir Level":"HBarray",
  "Heatherbank Pump 1 Current":"hb_P1_CURRENT_arr",
  "Heatherbank Pump 2 Current":"hb_P2_CURRENT_arr",
  "Heatherbank Pump 3 Current":"hb_P3_CURRENT_arr",
  "Heatherbank Pump 1 Run Hours":"hb_P1_RH_arr",
  "Heatherbank Pump 2 Run Hours":"hb_P2_RH_arr",
  "Heatherbank Pump 3 Run Hours":"hb_P3_RH_arr",
  "Lovemore Heights Reservoir Level":"LHarray",
  "Lovemore Heights Overhead Tank":"DRS_LH_RES_LVL_arr",
  "Blue Horizon Bay Reservoir Level":"BHB_array",
  "Theescombe Reservoir Level" :"TCarray",
  "Rosedale Reservoir Level":"RD_LVL_array",
  "Summit Reservoir Level":"SM_LVL_array",
  "Summit Flow Rate":"SM_FR_array",
  "Grassridge Inlet Flow":"GR_R_INLET_Arr",
  "Grassridge Outlet Flow":"GR_R_OUTLET_Arr",
  "Bethelsdorp Battery Level" :"BETH_BATTERY_STATUS_array",
  "Bethelsdorp Total Flow" :"BETH_TOTAL_FLOW_array",
  "Bethelsdorp Pressure" :"BETH_PRESS_array",
  "Bethelsdorp Flow Rate" :"BETH_FLOW_RATE_array",
  "FM Tower Flow Rate":"FMT_FR_array",
  "FM Tower Total Flow" :"FMT_TF_array",
  "FM Tower Pressure" :"FMT_PRESS_array",
  "Coega IDZ Flow Rate" :"IDZ_FR_array",
  "Coega Motherwell Flow Rate"  :"IDZ_MW_FR_array",
  "Gamtoos Bridge Steel Pipe Flow Rate":"GT_BRG_STL_FR_array",
  "Gamtoos Bridge Socoman Pipe Flow Rate":"GT_BRG_SOCO_FR_array",
  "Gamtoos Bridge Steel Pipe Pressure" :"GT_BRG_STL_PRESS_array",
  "Gamtoos Bridge Socoman Pipe Pressure" :"GT_BRG_SOCO_PRESS_array",
  "Uitenhage Flow Chamber Flow Rate" :"UIT_FC_FR_array",
  "Uitenhage Flow Chamber Pressure" :"UIT_FC_PRESS_array",
  "Humerail Borehol Level":"HUM_GW_BOR_LVL_arr",
  "Humerail Raw Water Tank Level" :"HUM_GW_RAW_WATER_TANK_LVL_arr",
  "Humerail Final Water Tank Level" :"HUM_GW_FIN_WAT_TANK_LVL_arr",
  "Storms River Quarry Level":"STORMS_QUARRY_LEVEL_Arr",
  "Storms River Gorge Level":"STORMS_GORGE_LEVEL_Arr",
  "Storms River Holding Reservoir Level" :"STORMS_HOLDING_RESERVOIR_LEVEL_Arr",
  "Storms River Overhead Tank Level":"STORMS_OVERHEAD_TANK_LEVEL_Arr",
  "Crown Gardens Suction Pressure":"CG_CSP_Arr",
  "Crown Gardens Delivery Pressure":"CG_CDP_Arr",
  "Crown Gardens Sump Level":"CG_S_LVL_Arr",
  "Crown Gardens Tower 1 Level":"CG_T1_LVL_Arr",
  "Crown Gardens Tower 1 Inlet Flow":"CG_T1_IF_Arr",
  "Crown Gardens Tower 1 Outlet Flow":"CG_T1_OF_Arr",
  "Crown Gardens Tower 2 Level":"CG_T2_LVL_Arr",
  "Crown Gardens Tower 2 Inlet Flow":"CG_T2_IF_Arr",
  "Crown Gardens Tower 2 Outlet Flow" :"CG_T2_OF_Arr",
  "NMU Effluent Delivery Pressure" :"NMU_EFF_DP_Arr",
  "NMU Effluent Flow Rate" :"NMU_EFF_FR_Arr",
  "NMU Effluent Dam Level" :"NMU_EFF_DAM_LVL_Arr",
  "NMU Effluent Pump 1 Speed" :"NMU_EFF_P1_SPEED_Arr",
  "NMU Effluent Pump 2 Speed" :"NMU_EFF_P2_SPEED_Arr",
  "NMU Effluent Pump 3 Speed":"NMU_EFF_P3_SPEED_Arr",
  "NMU Effluent Jockey Pump Speed":"NMU_EFF_JP_SPEED_Arr",
  "Chelsea Pumpstation 1 Actual Speed":"CHE_PS_P1_ACTUAL_SPEED_Arr",
  "Chelsea Pumpstation 1 Delivery Pressure":"CHE_PS_P1_DEL_PRESS_Arr",
  "Chelsea Pumpstation 1 Suction Pressure":"CHE_PS_P1_SUCT_PRESS_Arr",
  "Chelsea Pumpstation 2 Actual Speed":"CHE_PS_P2_ACTUAL_SPEED_Arr",
  "Chelsea Pumpstation 2 Delivery Pressure" :"CHE_PS_P2_DEL_PRESS_Arr",
  "Chelsea Pumpstation 2 Suction Pressure":"CHE_PS_P2_SUCT_PRESS_Arr",
  "Chelsea Pumpstation 3 Actual Speed":"CHE_PS_P3_ACTUAL_SPEED_Arr",
  "Chelsea Pumpstation 3 Delivery Pressure":"CHE_PS_P3_DEL_PRESS_Arr",
  "Chelsea Pumpstation 3 Suction Pressure":"CHE_PS_P3_SUCT_PRESS_Arr",
  "Chelsea Pumpstation 4 Actual Speed":"CHE_PS_P4_ACTUAL_SPEED_Arr",
  "Chelsea Pumpstation 4 Delivery Pressure":"CHE_PS_P4_DEL_PRESS_Arr",
  "Chelsea Pumpstation 4 Suction Pressure":"CHE_PS_P4_SUCT_PRESS_Arr",
  "Chelsea Pumpstation 700 Flow Rate":"CHE_PS_700_FLOW_RATE_Arr",
  "Chelsea Pumpstation 700 Total Flow":"CHE_PS_700_TOTAL_FLOW_Arr",
  "Newton Park Pool Pressure":"NMBM_NPP_GW_PRESSURE_Arr",
  "Newton Park Pool Flow Rate":"NMBM_NPP_GW_FLOW_RATE_Arr",
  "Newton Park Pool Water Level":"NMBM_NPP_GW_LEVEL_Arr",
  "Newton Park Pool Total Flow":"NMBM_NPP_GW_TOTAL_FLOW_Arr",
  "HD1 Water Level":"KLM_HUP_WATER_LEVEL_Arr",
  "HD1 Flow Rate":"KLM_HUP_FLOWRATE_Arr",
  "HD1 Total Flow":"KLM_HUP_TOTALFLOW_Arr",
  "HD2C Water Level":"KLM_HUP2_WATER_LEVEL_Arr",
  "HD2C Flow Rate":"KLM_HUP2_FLOWRATE_Arr",
  "HD2C Total Flow":"KLM_HUP2_TOTALFLOW_Arr",
  "HD3 Water Level":"KLM_HUP3_WATER_LEVEL_Arr",
  "HD3 Flow Rate":"KLM_HUP3_FLOWRATE_Arr",
  "HD3 Total Flow":"KLM_HUP3_TOTALFLOW_Arr",
  "HD4 Water Level":"KLM_HUP4_WATER_LEVEL_Arr",
  "HD4 Flow Rate":"KLM_HUP4_FLOWRATE_Arr",
  "HD4 Total Flow":"KLM_HUP4_TOTALFLOW_Arr",
  "HD6 Water Level":"KLM_HUP6_WATER_LEVEL_Arr",
  "HD6 Flow Rate":"KLM_HUP6_FLOWRATE_Arr",
  "HD6 Total Flow":"KLM_HUP6_TOTALFLOW_Arr",
  "Stanford Road Delivery Pressure":"STAN_BPS_DeliveryPressure_Arr",
  "Stanford Road Suction Pressure":"STAN_BPS_SuctionPressure_Arr",
  "Stanford Road Flow Rate":"STAN_BPS_FlowRate_Arr",
"Stanford Road Pump 1 Frequency":"STAN_BPS_P1_FREQ_Arr",
"Stanford Road Pump 2 Frequency":"STAN_BPS_P2_FREQ_Arr",
"Stanford Road Pump 3 Frequency":"STAN_BPS_P3_FREQ_Arr",
"Stanford Road Pump 4 Frequency":"STAN_BPS_P4_FREQ_Arr",
"Motherwell Delivery Pressure":"MW_BPS_DeliveryPressure_Arr",
  "Motherwell Flow Rate":"MW_BPS_FlowRate_Arr",
  "Motherwell Suction Pressure":"MW_BPS_SuctionPressure_Arr",
  "Motherwell Reservoir North Chamber Level":"MW_NORTH_LVL_array",
  "Motherwell Reservoir South Chamber Level":"MW_SOUTH_LVL_array",




  "Motherwell Total Flow":"MW_P_TF_arr",
  "Motherwell Pump 1 Speed":"MW_P1_PUMP_RPM_arr",
  "Motherwell Pump 2 Speed":"MW_P2_PUMP_RPM_arr",
  "Motherwell Pump 3 Speed":"MW_P3_PUMP_RPM_arr",
  "Motherwell Pump 4 Speed":"MW_P4_PUMP_RPM_arr",

  "Nooitgedacht High Level Flow Rate":"WTW_NGT_FM_HIGH_FR_Arr",
  "Nooitgedacht Low Level Flow Rate":"WTW_NGT_FM_LOW_FR_Arr",
  "St Georges Borehole Flow Rate":"st_georges_wtw_gw_FR_arr",
  "St Georges Borehole Total Flow":"st_georges_wtw_gw_TF_arr",
  "St Georges Emerald Hill Flow Rate":"st_georges_wtw_emer_hill_FR_arr",
  "St Georges Emerald Hill Total Flow":"st_georges_wtw_emer_hill_TF_arr",
  "Malabar Reservoir Level": "mala_lvl_arr",
  "Kruisfontein Borhole 12 Level":      "klm_kruis12_lvl_arr",
  "Kruisfontein Borhole 12 Current":    "klm_kruis12_current_arr",
  "Kruisfontein Borhole 12 Pressure":   "klm_kruis12_bar_arr",
  "Kruisfontein Borhole 12 Flow Rate":  "klm_kruis12_flow_rate_arr",
  "Kruisfontein Borhole 12 Total Flow": "klm_kruis12_total_flow_arr",
  "Kruisfontein Borhole 13 Level":      "klm_kruis13_lvl_arr",
  "Kruisfontein Borhole 13 Current":    "klm_kruis13_current_arr",
  "Kruisfontein Borhole 13 Pressure":   "klm_kruis13_bar_arr",
  "Kruisfontein Borhole 13 Flow Rate":  "klm_kruis13_flow_rate_arr",
  "Kruisfontein Borhole 13 Total Flow": "klm_kruis13_total_flow_arr",
  "Kruisfontein Borhole 14 Level":      "klm_kruis14_lvl_arr",
  "Kruisfontein Borhole 14 Current":    "klm_kruis14_current_arr",
  "Kruisfontein Borhole 14 Pressure":   "klm_kruis14_bar_arr",
  "Kruisfontein Borhole 14 Flow Rate":  "klm_kruis14_flow_rate_arr",
  "Kruisfontein Borhole 14 Total Flow": "klm_kruis14_total_flow_arr",
  "Humansdorp Inlet Flow Rate":         "klm_hup_wtw_flow_arr",
  "Humansdorp Inlet Total Flow":        "klm_hup_wtw_tf_arr",
  "Kruisfontein Reservoir Level":       "klm_kruis_res_lvl_arr",
  "Kwanobuhle Reservoir Level":         "KWANO_R_RES_LVL_arr",
  "Kwanobuhle Reservoir Flow Rate 1":   "KWANO_R_FLOW_RATE_1_arr",
  "Kwanobuhle Reservoir Flow Rate 2":   "KWANO_R_FLOW_RATE_2_arr",
  "Kwanobuhle Reservoir Total Flow 1":  "KWANO_R_TOTAL_FLOW_1_arr",
  "Kwanobuhle Reservoir Total Flow 2":  "KWANO_R_TOTAL_FLOW_2_arr",
  "Isuzu Oven 1 VSD Speed":"isuzu_oven1_vsd_speed_arr",
  "Isuzu Oven 1 Heat Exchanger Temperature":"isuzu_oven1_heat_ecvh_temp_arr",
  "Isuzu Oven 1 Temperature 1":"isuzu_oven1_temp1_arr",
  "Isuzu Oven 1 Temperature 2":"isuzu_oven1_temp2_arr",
  "Isuzu Oven 2 VSD Speed":"isuzu_oven2_vsd_speed_arr",
  "Isuzu Oven 2 Heat Exchanger Temperature":"isuzu_oven2_heat_ecvh_temp_arr",
  "Isuzu Oven 2 Temperature 1":"isuzu_oven2_temp1_arr",
  "Isuzu Oven 2 Temperature 2":"isuzu_oven2_temp2_arr",
  "Rosedale Reservoir Total Flow":"WDNR_ROSE_TF_arr",
  "Rosedale Reservoir Flow Rate":"WDNR_ROSE_FR_arr",
  "Rowallan Park Extension Pressure":"WDSR_ROWP_BAR_arr",
  "Rowallan Park Extension Total Flow":"WDSR_ROWP_TF_arr",
  "Rowallan Park Extension Flow Rate":"WDSR_ROWP_FR_arr",



  "Linton Back Wash Flow Rate":"lint_wtw_back_wash_FR_ARR",
  "Linton Back Wash Total Flow":"lint_wtw_back_wash_TF_ARR",
  "Linton Raw Water Flow Rate":"lint_wtw_raw_water_FR_ARR",
  "Linton Raw Water Total Flow":"lint_wtw_raw_water_TF_ARR",
  "Linton Final Water Flow Rate":"lint_wtw_final_water_FR_ARR",
  "Linton Final Water Total Flow":"lint_wtw_final_water_TF_ARR",
  "Linton Reservoir Level":"lint_res_lvl_ARR",


  }

  export const axisMap = {

    "Paradise Beach Flow Rate":"para_flow_rate_axis",
    "Paradise Beach Total Flow":"para_total_flow_axis",
    "Paradise Beach St Francis Total Flow":"para_st_flow_rate_axis",
    "Paradise Beach St Francis Flow Rate":"para_st_total_flow_axis",

    "Hankey Sewage Pumpstation 1 Total Flow":"hank_ps_g_total_flow_1_axis",
    "Hankey Sewage Pumpstation 2 Total Flow":"hank_ps_g_total_flow_2_axis",
    "Hankey Sewage Pumpstation SUMP Level":"hank_ps_g_sump_level_axis",
    "Hankey Sewage Pumpstation 1 Flow Rate":"hank_ps_g_flow_rate_1_axis",
    "Hankey Sewage Pumpstation 2 Flow Rate":"hank_ps_g_flow_rate_2_axis",
    "Hankey Sewage Pumpstation 1 Speed":"hank_ps_p1_speed_axis",
    "Hankey Sewage Pumpstation 2 Speed":"hank_ps_p2_speed_axis",
    "Hankey Sewage Pumpstation 3 Speed":"hank_ps_p3_speed_axis",

    "Glendinningvale Pump 1 Run Time":"glen_FTP_WTW_P1_rtm_axis",
    "Glendinningvale Pump 2 Run Time":"glen_FTP_WTW_P2_rtm_axis",
    "Glendinningvale Pump 1 Number Of Starts":"glen_FTP_WTW_P1_stn_axis",
    "Glendinningvale Pump 2 Number Of Starts":"glen_FTP_WTW_P2_stn_axis",
    "Glendinningvale Potential of Hydrogen":"glen_FTP_WTW_ph_axis",
    "Glendinningvale Oxidation Reduction Potential":"glen_FTP_WTW_orp_axis",

    "Glendinningvale Inlet Flow Rate":"glen_FTP_WTW_Inlet_Flow_Rate_axis",
    "Glendinningvale Inlet Total Flow":"glen_FTP_WTW_Inlet_Total_Flow_axis",
    "Glendinningvale Inlet Pressure":"glen_FTP_WTW_Inlet_bar_axis",
    "Glendinningvale Borehole Flow Rate":"glen_FTP_WTW_borehole_Flow_Rate_axis",
    "Glendinningvale Borehole Total Flow":"glen_FTP_WTW_borehole_Total_Flow_axis",
    "Glendinningvale Reservoir Level":"glen_r_res_lvl_axis",
    "Kareedouw K1 Total Flow":"KARK_K1_TF_axis",
    "Kareedouw K1 Flow Rate":"KARK_K1_FR_axis",
    "Kareedouw K1 Current":"KARK_K1_CUR_axis",
    "Kareedouw K1 Level":"KARK_K1_LVL_axis",
    "Kareedouw K2 Total Flow":"KARK_K2_TF_axis",
    "Kareedouw K2 Flow Rate":"KARK_K2_FR_axis",
    "Kareedouw K2 Current":"KARK_K2_CUR_axis",
    "Kareedouw K2 Level":"KARK_K2_LVL_axis",
    "Greenbushes Reservoir Level":"GB_axis",
    "Greenbushes Flow Rate":"GBFR_axis",
    "Elandsjagt Flow Rate":"ELA_FR_axis",
    "Elandsjagt Pressure":"ELA_P_axis",
    "Emerald Hill Reservoir Level":"EMER_H_LEVEL_axis",
    "Schoemanshoek Pressure":"NMB_SCHOE_PRESSURE_axis",
    "Schoemanshoek Level":"NMB_SCHOE_RES_LEVEL_axis",
    "Schoemanshoek Actuator Position":"NMB_SCHOE_ACTUATOR_POSITION_axis",
    "Schoemanshoek Actuator Set Point":"NMB_SCHOE_ACTUATOR_SET_POINT_axis",
    "Driftsands Reservoir Level":"drift_res_level_axis",
    "Driftsands Flow Rate 1" :"drift_res_flow_rate_1_axis",
    "Driftsands Flow Rate 2":"drift_res_flow_rate_2_axis",
    "Driftsands Total Flow 1":"drift_res_total_flow_1_axis",
    "Driftsands Total Flow 2":"drift_res_total_flow_2_axis",
    "Airport Reservoir Level":"AIR_PRT_LVL_axis",
    "Lee Samuals Drive Pressure":"LSD_PRESSURE_axis",
    "Lee Samuals Drive Total Flow":"LSD_TOTAL_FLOW_axis",
    "Lee Samuals Drive Flow Rate":"LSD_FLOW_RATE_axis",
    "McNoughton Township South Pressure":"McNougTown_PRESSURE_axis",
    "McNoughton Township South Total Flow":"McNougTown_TOTAL_FLOW_axis",
    "McNoughton Township South Flow Rate":"McNougTown_FLOW_RATE_axis",
    "Schoemanshoek Actuator Valve Feedback Signal":"nmb_schoe_r_actuator_valve_feedback_signal_error_axis",
    "Schoemanshoek Actuator Valve Command Signal":"nmb_schoe_r_actuator_valve_command_signal_error_axis",
    "Schoemanshoek Reservoir Level Signal Error":"nmb_schoe_r_reservoir_level_signal_error_axis",
    "Schoemanshoek Actuator Valve Fault":"nmb_schoe_r_actuator_valve_fault_axis",
    "Schoemanshoek Actuator Valve Torque Fail Close":"nmb_schoe_r_actuator_valve_torque_fail_close_axis",
    "Schoemanshoek Actuator Valve Torque Fail Open":"nmb_schoe_r_actuator_valve_torque_fail_open_axis",
    "Schoemanshoek General Fault":"nmb_schoe_r_general_fault_axis",
    "Schoemanshoek Actuator General Fault":"nmb_schoe_r_actuator_general_fault_axis",
    "Schoemanshoek Actuator Valve Timeout":"nmb_schoe_r_actuator_valve_timeout_axis",
    "Bergendal Reservoir Level":"BERGEN_RES_R_LVL_axis",
    "Umasizakhe Reservoir Level" :"UMI_RES_R_LVL_axis",
    "Wolwas Reservoir Level":"WOLWAS_RES_R_LVL_axis",
  "Kroonvale Reservoir Level"  :"KROON_RES_R_LVL_axis",
  "Tin Roof Reservoir Level"  :"TINROOF_LVL_RES_LVL_axis",
  "Damcamp Reservoir Level" :"DAMCAMP_LVL_RES_LVL_axis",
  "Holding Reservoir Level" :"HOLDING_LVL_RES_LVL_axis",
  "Bushy Park Soccoman Flow Rate":"BUSH_CHURCH_SOCO_FR_axis",
  "Bushy Park Steel Flow Rate":"BUSH_CHURCH_STEEL_FR_axis",
  "Bushy Park Soccoman Pressure":"BUSH_CHURCH_SOCCO_BAR_axis",
  "Bushy Park Steel Pressure":"BUSH_CHURCH_STEEL_BAR_axis",
  "Bushy Park Pumpstation Flow Rate":"BUSH_PUMP_FR_axis",
  "Bushy Park Combined Borehole Flow Rate":"BUSH_GW_COMB_FLOW_RATE_axis",
  "Bushy Park Holding Tank Level":"BUSH_TANK_LVL_axis",
  "Bushy Park Combined Total Flow":"BUSH_GW_TF_axis",
  "Bushy Park Pumpstation Total Flow":"BUSH_PUMP_TF_axis",
  "Bushy Park Steel Total Flow":"BUSH_STEEL_TF_axis",
  "Bushy Park Soccoman Total Flow":"BUSH_SOCO_TF_axis",
  "Humansdorp Off Take Total Flow"  :"HUM_OFF_TAKE_TF_axis",
  "Humansdorp Off Take Pressure" :"HUM_OFF_TAKE_BAR_axis",
  "Humansdorp Off Take Battery Level" :"HUM_OFF_TAKE_BAT_axis",
  "Jeffreys Bay Off Take Total Flow" :"JEFF_OFF_TAKE_TF_axis",
  "Jeffreys Bay Off Take Battery Level":"JEFF_OFF_TAKE_BAT_axis",
  "Kouga Main Line Pressure":"KOU_MAIN_LINE_BAR_axis",
  "Kouga Main Line Battery Level" :"KOU_MAIN_LINE_BAT_axis",
  "Ons Paradys Total Flow":"ONS_PARA_TF_axis",
  "Ons Paradys Battery Level":"ONS_PARA_BAT_axis",
  "St Francis Offtake Total Flow" :"ST_FRAN_OFF_TF_axis",
  "Paradise/St Francis Battery Level" :"ST_FRAN_PARA_BEA_BAT_axis",
  "Gamtoos Break Water Pressure" :"GBW_ACT_BAR_axis",
  "Gamtoos Break Water Flow Rate" :"GBW_FLO_RAT_axis",
  "Emerald Hill Flow Rate" :"EMER_H_FLOW_RATE_axis",
  "Emerald Hill Total Flow" :"EMER_H_TOTAL_FLOW_axis",
  "Coega Kop Reservoir Pressure" :"CGK_PRESSURE_axis",
  "Olifantskop Reservoir Level" :"OLI_LVL_axis",
  "Coega Kop to Coega IDZ Flow Rate" :"CGK_COEGA_FLOW_RATE_axis",
  "Coega Kop to Motherwell Total Flow":"CGK_MOTHERWELL_TOTAL_FLOW_axis",
  "Coega Kop from Grassridge Total Flow" :"CGK_GRASSRIDGE_TOTAL_FLOW_axis",
  "Coega Kop to Coega IDZ Total Flow" :"CGK_COEGA_TOTAL_FLOW_axis",
  "Coega Kop Inlet Chamber 2 Ml"  :"CGK_LEVEL_axis",
  "Coega Kop to Motherwell Flow Rate":"CGK_MOTHERWELL_FLOW_RATE_axis",
  "Coega Kop from Grassridge Flow Rate":"CGK_GRASSRIDGE_FLOW_RATE_axis",
  "Chelsea Reservoir East Chamber Level":"CHE_East_axis",
  "Chelsea Reservoir West Chamber Level":"CHE_West_axis",
  "Chelsea Reservoir Summit 1200 mm Flow Rate":"CHE_R_FR1200_axis",
  "Chelsea Reservoir Greenbushes 600 mm Flow Rate":"CHE_R_FR600_axis",
  "Chelsea Reservoir Summit 1200 mm Total Flow":"CHE_R_TF1200_axis",
  "Chelsea Reservoir Greenbushes 600 mm Total Flow":"CHE_R_TF600_axis",
  "Chatty Flow Rate" :"CHE_fr_axis",
  "Grassridge East Chamber Level" :"GR_EC_axis",
  "Grassridge West Chamber Level":"GR_WC_axis",
  "Van Stadens Reservoir Level":"VS_axis",
  "Chatty North Chamber Level":"CHT_NC_axis",
  "Chatty Overhead Level":"CHT_OR_axis",
  "Chatty South Chamber Level":"CHT_SC_axis",
  "Van Riebeeck Hoogte Delivery Level":"VRH_DL_axis",
  "Van Riebeeck Hoogte Suction Level":"VRH_SL_axis",
  "Heatherbank Reservoir Level":"HB_axis",
  "Heatherbank Pump 1 Current":"hb_P1_CURRENT_axis",
  "Heatherbank Pump 2 Current":"hb_P2_CURRENT_axis",
  "Heatherbank Pump 3 Current":"hb_P3_CURRENT_axis",
  "Heatherbank Pump 1 Run Hours":"hb_P1_RH_axis",
  "Heatherbank Pump 2 Run Hours":"hb_P2_RH_axis",
  "Heatherbank Pump 3 Run Hours":"hb_P3_RH_axis",
  "Lovemore Heights Reservoir Level":"LH_axis",
  "Lovemore Heights Overhead Tank":"DRS_LH_RES_LVL_axis",
  "Blue Horizon Bay Reservoir Level":"BHB_axis",
  "Theescombe Reservoir Level" :"TC_axis",
  "Rosedale Reservoir Level":"RD_LVL_axis",
  "Summit Reservoir Level":"SM_LVL_axis",
  "Summit Flow Rate":"SM_FR_axis",
  "Grassridge Inlet Flow":"GR_R_INLET_axis",
  "Grassridge Outlet Flow":"GR_R_OUTLET_axis",
  "Bethelsdorp Battery Level" :"BETH_BATTERY_STATUS_axis",
  "Bethelsdorp Total Flow" :"BETH_TOTAL_FLOW_axis",
  "Bethelsdorp Pressure" :"BETH_PRESS_axis",
  "Bethelsdorp Flow Rate" :"BETH_FLOW_RATE_axis",
  "FM Tower Flow Rate":"FMT_FR_axis",
  "FM Tower Total Flow" :"FMT_TF_axis",
  "FM Tower Pressure" :"FMT_PRESS_axis",
  "Coega IDZ Flow Rate" :"IDZ_FR_axis",
  "Coega Motherwell Flow Rate"  :"IDZ_MW_FR_axis",
  "Gamtoos Bridge Steel Pipe Flow Rate":"GT_BRG_STL_FR_axis",
  "Gamtoos Bridge Socoman Pipe Flow Rate":"GT_BRG_SOCO_FR_axis",
  "Gamtoos Bridge Steel Pipe Pressure" :"GT_BRG_STL_PRESS_axis",
  "Gamtoos Bridge Socoman Pipe Pressure" :"GT_BRG_SOCO_PRESS_axis",
  "Uitenhage Flow Chamber Flow Rate" :"UIT_FC_FR_axis",
  "Uitenhage Flow Chamber Pressure" :"UIT_FC_PRESS_axis",
  "Humerail Borehol Level":"HUM_GW_BOR_LVL_axis",
  "Humerail Raw Water Tank Level" :"HUM_GW_RAW_WATER_TANK_LVL_axis",
  "Humerail Final Water Tank Level" :"HUM_GW_FIN_WAT_TANK_LVL_axis",
  "Storms River Quarry Level":"STORMS_QUARRY_LEVEL_axis",
  "Storms River Gorge Level":"STORMS_OVERHEAD_TANK_LEVEL_axis",
  "Storms River Holding Reservoir Level" :"STORMS_HOLDING_RESERVOIR_LEVEL_axis",
  "Storms River Overhead Tank Level":"STORMS_GORGE_LEVEL_axis",
  "Crown Gardens Suction Pressure":"CG_CSP_axis",
  "Crown Gardens Delivery Pressure":"CG_CDP_axis",
  "Crown Gardens Sump Level":"CG_S_LVL_axis",
  "Crown Gardens Tower 1 Level":"CG_T1_LVL_axis",
  "Crown Gardens Tower 1 Inlet Flow":"CG_T1_IF_axis",
  "Crown Gardens Tower 1 Outlet Flow":"CG_T1_OF_axis",
  "Crown Gardens Tower 2 Level":"CG_T2_LVL_axis",
  "Crown Gardens Tower 2 Inlet Flow":"CG_T2_IF_axis",
  "Crown Gardens Tower 2 Outlet Flow" :"CG_T2_OF_axis",
  "NMU Effluent Delivery Pressure" :"NMU_EFF_DP_axis",
  "NMU Effluent Flow Rate" :"NMU_EFF_FR_axis",
  "NMU Effluent Dam Level" :"NMU_EFF_DAM_LVL_axis",
  "NMU Effluent Pump 1 Speed" :"NMU_EFF_P1_SPEED_axis",
  "NMU Effluent Pump 2 Speed" :"NMU_EFF_P2_SPEED_axis",
  "NMU Effluent Pump 3 Speed":"NMU_EFF_P3_SPEED_axis",
  "NMU Effluent Jockey Pump Speed":"NMU_EFF_JP_SPEED_axis",
  "Chelsea Pumpstation 1 Actual Speed":"CHE_PS_P1_ACTUAL_SPEED_Axis",
  "Chelsea Pumpstation 1 Delivery Pressure":"CHE_PS_P1_DEL_PRESS_Axis",
  "Chelsea Pumpstation 1 Suction Pressure":"CHE_PS_P1_SUCT_PRESS_Axis",
  "Chelsea Pumpstation 2 Actual Speed":"CHE_PS_P2_ACTUAL_SPEED_Axis",
  "Chelsea Pumpstation 2 Delivery Pressure" :"CHE_PS_P2_DEL_PRESS_Axis",
  "Chelsea Pumpstation 2 Suction Pressure":"CHE_PS_P2_SUCT_PRESS_Axis",
  "Chelsea Pumpstation 3 Actual Speed":"CHE_PS_P3_ACTUAL_SPEED_Axis",
  "Chelsea Pumpstation 3 Delivery Pressure":"CHE_PS_P3_DEL_PRESS_Axis",
  "Chelsea Pumpstation 3 Suction Pressure":"CHE_PS_P3_SUCT_PRESS_Axis",
  "Chelsea Pumpstation 4 Actual Speed":"CHE_PS_P4_ACTUAL_SPEED_Axis",
  "Chelsea Pumpstation 4 Delivery Pressure":"CHE_PS_P4_DEL_PRESS_Axis",
  "Chelsea Pumpstation 4 Suction Pressure":"CHE_PS_P4_SUCT_PRESS_Axis",
  "Chelsea Pumpstation 700 Flow Rate":"CHE_PS_700_FLOW_RATE_Axis",
"Chelsea Pumpstation 700 Total Flow":"CHE_PS_700_TOTAL_FLOW_Axis",
  "Newton Park Pool Pressure":"NMBM_NPP_GW_PRESSURE_axis",
  "Newton Park Pool Flow Rate":"NMBM_NPP_GW_FLOW_RATE_axis",
  "Newton Park Pool Water Level":"NMBM_NPP_GW_LEVEL_axis",
  "Newton Park Pool Total Flow":"NMBM_NPP_GW_TOTAL_FLOW_axis",
  "HD1 Water Level":"KLM_HUP_WATER_LEVEL_Axis",
  "HD1 Flow Rate":"KLM_HUP_FLOWRATE_Axis",
  "HD1 Total Flow":"KLM_HUP_TOTALFLOW_Axis",
  "HD2C Water Level":"KLM_HUP2_WATER_LEVEL_Axis",
  "HD2C Flow Rate":"KLM_HUP2_FLOWRATE_Axis",
  "HD2C Total Flow":"KLM_HUP2_TOTALFLOW_Axis",
  "HD3 Water Level":"KLM_HUP3_WATER_LEVEL_Axis",
  "HD3 Flow Rate":"KLM_HUP3_FLOWRATE_Axis",
  "HD3 Total Flow":"KLM_HUP3_TOTALFLOW_Axis",
  "HD4 Water Level":"KLM_HUP4_WATER_LEVEL_Axis",
  "HD4 Flow Rate":"KLM_HUP4_FLOWRATE_Axis",
  "HD4 Total Flow":"KLM_HUP4_TOTALFLOW_Axis",
  "HD6 Water Level":"KLM_HUP6_WATER_LEVEL_Axis",
  "HD6 Flow Rate":"KLM_HUP6_FLOWRATE_Axis",
  "HD6 Total Flow":"KLM_HUP6_TOTALFLOW_Axis",
  "Stanford Road Delivery Pressure":"STAN_BPS_DeliveryPressure_axis",
  "Stanford Road Suction Pressure":"STAN_BPS_SuctionPressure_axis",
  "Stanford Road Flow Rate":"STAN_BPS_FlowRate_axis",
"Stanford Road Pump 1 Frequency":"STAN_BPS_P1_FREQ_axis",
"Stanford Road Pump 2 Frequency":"STAN_BPS_P2_FREQ_axis",
"Stanford Road Pump 3 Frequency":"STAN_BPS_P3_FREQ_axis",
"Stanford Road Pump 4 Frequency":"STAN_BPS_P4_FREQ_axis",
"Motherwell Delivery Pressure":"MW_BPS_DeliveryPressure_axis",
  "Motherwell Flow Rate":"MW_BPS_FlowRate_axis",
  "Motherwell Suction Pressure":"MW_BPS_SuctionPressure_axis",
"  Motherwell Reservoir North Chamber Level":"MW_NORTH_LVL_axis",
"  Motherwell Reservoir South Chamber Level":"MW_SOUTH_LVL_axis",


  "Motherwell Total Flow":"MW_P_TF_axis",
  "Motherwell Pump 1 Speed":"MW_P1_PUMP_RPM_axis",
  "Motherwell Pump 2 Speed":"MW_P2_PUMP_RPM_axis",
  "Motherwell Pump 3 Speed":"MW_P3_PUMP_RPM_axis",
  "Motherwell Pump 4 Speed":"MW_P4_PUMP_RPM_axis",


  "Nooitgedacht High Level Flow Rate":"WTW_NGT_FM_HIGH_FR_axis",
  "Nooitgedacht Low Level Flow Rate":"WTW_NGT_FM_LOW_FR_axis",
  "St Georges Borehole Flow Rate":"",
  "St Georges Borehole Total Flow":"st_georges_wtw_gw_FR_axis",
  "St Georges Emerald Hill Flow Rate":"st_georges_wtw_emer_hill_FR_axis",
  "St Georges Emerald Hill Total Flow":"st_georges_wtw_emer_hill_TF_axis",
  "Malabar Reservoir Level": "mala_lvl_axis",
  "Kruisfontein Borhole 12 Level":      "klm_kruis12_lvl_axis",
  "Kruisfontein Borhole 12 Current":    "klm_kruis12_current_axis",
  "Kruisfontein Borhole 12 Pressure":   "klm_kruis12_bar_axis",
  "Kruisfontein Borhole 12 Flow Rate":  "klm_kruis12_flow_rate_axis",
  "Kruisfontein Borhole 12 Total Flow": "klm_kruis12_total_flow_axis",
  "Kruisfontein Borhole 13 Level":      "klm_kruis13_lvl_axis",
  "Kruisfontein Borhole 13 Current":    "klm_kruis13_current_axis",
  "Kruisfontein Borhole 13 Pressure":   "klm_kruis13_bar_axis",
  "Kruisfontein Borhole 13 Flow Rate":  "klm_kruis13_flow_rate_axis",
  "Kruisfontein Borhole 13 Total Flow": "klm_kruis13_total_flow_axis",
  "Kruisfontein Borhole 14 Level":      "klm_kruis14_lvl_axis",
  "Kruisfontein Borhole 14 Current":    "klm_kruis14_current_axis",
  "Kruisfontein Borhole 14 Pressure":   "klm_kruis14_bar_axis",
  "Kruisfontein Borhole 14 Flow Rate":  "klm_kruis14_flow_rate_axis",
  "Kruisfontein Borhole 14 Total Flow": "klm_kruis14_total_flow_axis",
  "Humansdorp Inlet Flow Rate":         "klm_hup_wtw_flow_axis",
  "Humansdorp Inlet Total Flow":        "klm_hup_wtw_tf_axis",
  "Kruisfontein Reservoir Level":       "klm_kruis_res_lvl_axis",
  "Kwanobuhle Reservoir Level":         "KWANO_R_RES_LVL_axis",
  "Kwanobuhle Reservoir Flow Rate 1":   "KWANO_R_FLOW_RATE_1_axis",
  "Kwanobuhle Reservoir Flow Rate 2":   "KWANO_R_FLOW_RATE_2_axis",
  "Kwanobuhle Reservoir Total Flow 1":  "KWANO_R_TOTAL_FLOW_1_axis",
  "Kwanobuhle Reservoir Total Flow 2":  "KWANO_R_TOTAL_FLOW_2_axis",
  "Isuzu Oven 1 VSD Speed":"isuzu_oven1_vsd_speed_axis",
  "Isuzu Oven 1 Heat Exchanger Temperature":"isuzu_oven1_heat_ecvh_temp_axis",
  "Isuzu Oven 1 Temperature 1":"isuzu_oven1_temp1_axis",
  "Isuzu Oven 1 Temperature 2":"isuzu_oven1_temp2_axis",
  "Isuzu Oven 2 VSD Speed":"isuzu_oven2_vsd_speed_axis",
  "Isuzu Oven 2 Heat Exchanger Temperature":"isuzu_oven2_heat_ecvh_temp_axis",
  "Isuzu Oven 2 Temperature 1":"isuzu_oven2_temp1_axis",
  "Isuzu Oven 2 Temperature 2":"isuzu_oven2_temp2_axis",
    "Rosedale Reservoir Total Flow":"WDNR_ROSE_TF_axis",
    "Rosedale Reservoir Flow Rate":"WDNR_ROSE_FR_axis",
    "Rowallan Park Extension Pressure":"WDSR_ROWP_BAR_axis",
    "Rowallan Park Extension Total Flow":"WDSR_ROWP_TF_axis",
    "Rowallan Park Extension Flow Rate":"WDSR_ROWP_FR_axis",

    "Linton Back Wash Flow Rate":"lint_wtw_back_wash_FR_Axis",
    "Linton Back Wash Total Flow":"lint_wtw_back_wash_TF_Axis",
    "Linton Raw Water Flow Rate":"lint_wtw_raw_water_FR_Axis",
    "Linton Raw Water Total Flow":"lint_wtw_raw_water_TF_Axis",
    "Linton Final Water Flow Rate":"lint_wtw_final_water_FR_Axis",
    "Linton Final Water Total Flow":"lint_wtw_final_water_TF_Axis",
    "Linton Reservoir Level":"lint_res_lvl_Axis",

  }


  export const axisValues={

    para_flow_rate_axis:0,
para_total_flow_axis:0,
para_st_flow_rate_axis:0,
para_st_total_flow_axis:0,

    hank_ps_g_total_flow_1_axis:0,
    hank_ps_g_total_flow_2_axis:0,
    hank_ps_g_sump_level_axis:0,
    hank_ps_g_flow_rate_1_axis:0,
    hank_ps_g_flow_rate_2_axis:0,
    hank_ps_p1_speed_axis:0,
    hank_ps_p2_speed_axis:0,
    hank_ps_p3_speed_axis:0,


    glen_FTP_WTW_P1_rtm_axis:0,
    glen_FTP_WTW_P2_rtm_axis:0,
    glen_FTP_WTW_P1_stn_axis:0,
    glen_FTP_WTW_P2_stn_axis:0,
    glen_FTP_WTW_ph_axis:0,
    glen_FTP_WTW_orp_axis:0,
    glen_FTP_WTW_Inlet_Flow_Rate_axis:0,
    glen_FTP_WTW_Inlet_Total_Flow_axis:0,
    glen_FTP_WTW_Inlet_bar_axis:0,
    glen_FTP_WTW_borehole_Flow_Rate_axis:0,
    glen_FTP_WTW_borehole_Total_Flow_axis:0,
    glen_r_res_lvl_axis:0,
    KWANO_R_RES_LVL_axis:0,
    KWANO_R_FLOW_RATE_1_axis:0,
    KWANO_R_FLOW_RATE_2_axis:0,
    KWANO_R_TOTAL_FLOW_1_axis:0,
    KWANO_R_TOTAL_FLOW_2_axis:0,
    GR_R_INLET_axis: 0,
    mala_lvl_axis:0,
    GR_R_OUTLET_axis :0,
    ELA_FR_axis :0,
    ELA_P_axis :0,
    HUM_GW_BOR_LVL_axis :0,
    HUM_GW_RAW_WATER_TANK_LVL_axis :0,
    HUM_GW_FIN_WAT_TANK_LVL_axis :0,
    drift_res_level_axis:0,
    drift_res_flow_rate_1_axis:0,
    drift_res_flow_rate_2_axis:0,
    drift_res_total_flow_1_axis:0,
    drift_res_total_flow_2_axis:0,
    AIR_PRT_LVL_axis:0,
    LSD_PRESSURE_axis:0,
LSD_TOTAL_FLOW_axis:0,
LSD_FLOW_RATE_axis:0,
McNougTown_PRESSURE_axis:0,
McNougTown_TOTAL_FLOW_axis:0,
McNougTown_FLOW_RATE_axis:0,
    nmb_schoe_r_actuator_valve_feedback_signal_error_axis :0,
    nmb_schoe_r_actuator_valve_command_signal_error_axis :0,
    nmb_schoe_r_reservoir_level_signal_error_axis :0,
    nmb_schoe_r_actuator_valve_fault_axis :0,
    nmb_schoe_r_actuator_valve_torque_fail_close_axis :0,
    nmb_schoe_r_actuator_valve_torque_fail_open_axis :0,
    nmb_schoe_r_general_fault_axis :0,
    nmb_schoe_r_actuator_general_fault_axis :0,
    nmb_schoe_r_actuator_valve_timeout_axis :0,
    BUSH_CHURCH_SOCO_FR_axis :0,
    BUSH_CHURCH_STEEL_FR_axis :0,
    BUSH_CHURCH_SOCCO_BAR_axis :0,
    BUSH_CHURCH_STEEL_BAR_axis :0,
    BUSH_PUMP_FR_axis :0,
    BUSH_GW_COMB_FLOW_RATE_axis :0,
    BUSH_TANK_LVL_axis :0,
    BUSH_GW_TF_axis:0,
    BUSH_PUMP_TF_axis:0,
    BUSH_STEEL_TF_axis:0,
    BUSH_SOCO_TF_axis:0,
    HUM_OFF_TAKE_TF_axis :0,
    HUM_OFF_TAKE_BAR_axis :0,
    HUM_OFF_TAKE_BAT_axis:0,
    JEFF_OFF_TAKE_TF_axis :0,
    JEFF_OFF_TAKE_BAT_axis:0,
    KOU_MAIN_LINE_BAR_axis :0,
    KOU_MAIN_LINE_BAT_axis :0,
    ONS_PARA_TF_axis :0,
    ONS_PARA_BAT_axis :0,
    ST_FRAN_OFF_TF_axis :0,
    PARA_BEA_TF_axis :0,
    ST_FRAN_PARA_BEA_BAT_axis:0,
    GBW_ACT_BAR_axis :0,
    GBW_FLO_RAT_axis :0,
    EMER_H_LEVEL_axis:0,
    EMER_H_FLOW_RATE_axis :0,
    EMER_H_TOTAL_FLOW_axis :0,
    CGK_PRESSURE_axis:0 ,
    OLI_LVL_axis :0,
    KROON_RES_R_LVL_axis:0,
    UMI_RES_R_LVL_axis :0,
    WOLWAS_RES_R_LVL_axis :0,
    BERGEN_RES_R_LVL_axis :0,
    TINROOF_LVL_RES_LVL_axis :0,
    DAMCAMP_LVL_RES_LVL_axis :0,
    HOLDING_LVL_RES_LVL_axis :0,
    KARK_K1_TF_axis :0,
    KARK_K1_FR_axis :0,
    KARK_K1_CUR_axis :0,
    KARK_K1_LVL_axis :0,
    KARK_K2_TF_axis :0,
    KARK_K2_FR_axis :0,
    KARK_K2_CUR_axis :0,
    KARK_K2_LVL_axis :0,
    CGK_MOTHERWELL_TOTAL_FLOW_axis :0,
    CGK_COEGA_FLOW_RATE_axis:0,
    CGK_GRASSRIDGE_TOTAL_FLOW_axis :0,
    CGK_COEGA_TOTAL_FLOW_axis :0,
    CGK_LEVEL_axis:0,
    CGK_KOP_NC_17_ML_axis:0,
    CGK_MOTHERWELL_FLOW_RATE_axis :0,
    CGK_GRASSRIDGE_FLOW_RATE_axis :0,
    GB_axis :0,
    GBFR_axis :0,
    NMB_SCHOE_PRESSURE_axis :0,
    NMB_SCHOE_RES_LEVEL_axis :0,
    NMB_SCHOE_ACTUATOR_POSITION_axis:0,
    NMB_SCHOE_ACTUATOR_SET_POINT_axis :0,
    CHE_East_axis:0,
    CHE_West_axis:0,
    CHE_R_FR1200_axis:0,
    CHE_R_FR600_axis:0,
    CHE_R_TF1200_axis:0,
    CHE_R_TF600_axis:0,
    GR_EC_axis :0,
    CHE_fr_axis:0,
    GR_WC_axis :0,
    VS_axis :0,
    CHT_NC_axis :0,
    CHT_OR_axis :0,
    CHT_SC_axis :0,
    VRH_DL_axis :0,
    VRH_SL_axis :0,
    HB_axis :0,
    hb_P1_CURRENT_axis:0,
    hb_P2_CURRENT_axis:0,
    hb_P3_CURRENT_axis:0,
    hb_P1_RH_axis:0,
    hb_P2_RH_axis:0,
    hb_P3_RH_axis:0,
    LH_axis :0,
    DRS_LH_RES_LVL_axis:0,
    BHB_axis :0,
    TC_axis :0,
    RD_LVL_axis:0,
    SM_FR_axis:0,
    SM_LVL_axis:0,
    BETH_PRESS_axis:0,
    BETH_FLOW_RATE_axis:0,
    BETH_BATTERY_STATUS_axis:0,
    BETH_TOTAL_FLOW_axis:0,
    FMT_FR_axis :0,
    FMT_TF_axis:0,
    FMT_PRESS_axis :0,
    IDZ_FR_axis:0,
    IDZ_MW_FR_axis:0,
    GT_BRG_STL_FR_axis:0,
    GT_BRG_SOCO_FR_axis:0,
    GT_BRG_STL_PRESS_axis:0,
    GT_BRG_SOCO_PRESS_axis:0,
    UIT_FC_FR_axis:0,
    UIT_FC_PRESS_axis:0,
    CG_CSP_axis:0,
    CG_CDP_axis:0,
    CG_S_LVL_axis:0,
    CG_T1_LVL_axis:0,
    CG_T1_IF_axis:0,
    CG_T1_OF_axis:0,
    CG_T2_LVL_axis:0,
    CG_T2_IF_axis:0,
    CG_T2_OF_axis:0,
    NMU_EFF_FR_axis:0,
    NMU_EFF_DP_axis:0,
    NMU_EFF_DAM_LVL_axis:0,
    NMU_EFF_P1_SPEED_axis:0,
    NMU_EFF_P2_SPEED_axis:0,
    NMU_EFF_P3_SPEED_axis:0,
    NMU_EFF_JP_SPEED_axis:0,
    CHE_PS_P1_ACTUAL_SPEED_Axis :0,
    CHE_PS_P1_DEL_PRESS_Axis :0,
    CHE_PS_P1_SUCT_PRESS_Axis :0,
    CHE_PS_P2_ACTUAL_SPEED_Axis:0,
    CHE_PS_P2_DEL_PRESS_Axis:0,
    CHE_PS_P2_SUCT_PRESS_Axis:0,
    CHE_PS_P3_ACTUAL_SPEED_Axis:0,
    CHE_PS_P3_DEL_PRESS_Axis:0,
    CHE_PS_P3_SUCT_PRESS_Axis:0,
    CHE_PS_P4_ACTUAL_SPEED_Axis:0,
    CHE_PS_P4_DEL_PRESS_Axis:0,
    CHE_PS_P4_SUCT_PRESS_Axis:0,
    CHE_PS_700_FLOW_RATE_Axis:0,
    CHE_PS_700_TOTAL_FLOW_Axis:0,
    STORMS_QUARRY_LEVEL_axis:0,
    STORMS_GORGE_LEVEL_axis:0,
    STORMS_HOLDING_RESERVOIR_LEVEL_axis:0,
    STORMS_OVERHEAD_TANK_LEVEL_axis :0,
    NMBM_NPP_GW_PRESSURE_axis :0,
    NMBM_NPP_GW_FLOW_RATE_axis :0,
    NMBM_NPP_GW_LEVEL_axis :0,
    NMBM_NPP_GW_TOTAL_FLOW_axis:0,
    KLM_HUP_WATER_LEVEL_Axis:0,
    KLM_HUP_FLOWRATE_Axis:0,
    KLM_HUP_TOTALFLOW_Axis:0,
    KLM_HUP2_WATER_LEVEL_Axis:0,
    KLM_HUP2_FLOWRATE_Axis:0,
    KLM_HUP2_TOTALFLOW_Axis:0,
    KLM_HUP3_WATER_LEVEL_Axis:0,
    KLM_HUP3_FLOWRATE_Axis:0,
    KLM_HUP3_TOTALFLOW_Axis:0,
    KLM_HUP4_WATER_LEVEL_Axis:0,
    KLM_HUP4_FLOWRATE_Axis:0,
    KLM_HUP4_TOTALFLOW_Axis:0,
    KLM_HUP6_WATER_LEVEL_Axis:0,
    KLM_HUP6_FLOWRATE_Axis:0,
    KLM_HUP6_TOTALFLOW_Axis:0,
    STAN_BPS_SuctionPressure_axis :0,
    STAN_BPS_DeliveryPressure_axis :0,
    STAN_BPS_FlowRate_axis :0,
    STAN_BPS_P1_FREQ_axis :0,
    STAN_BPS_P2_FREQ_axis :0,
    STAN_BPS_P3_FREQ_axis :0,
    STAN_BPS_P4_FREQ_axis :0,
    MW_BPS_FlowRate_axis:0,
    MW_BPS_DeliveryPressure_axis:0,

    MW_NORTH_LVL_axis:0,
    MW_SOUTH_LVL_axis:0,


    MW_P_TF_axis:0,
    MW_P1_PUMP_RPM_axis:0,
    MW_P2_PUMP_RPM_axis:0,
    MW_P3_PUMP_RPM_axis:0,
    MW_P4_PUMP_RPM_axis:0,
    MW_BPS_SuctionPressure_axis :0,
    WTW_NGT_FM_LOW_FR_axis:0,
    WTW_NGT_FM_HIGH_FR_axis:0,
    st_georges_wtw_gw_FR_axis:0,
    st_georges_wtw_gw_TF_axis:0,
    st_georges_wtw_emer_hill_FR_axis:0,
    st_georges_wtw_emer_hill_TF_axis:0,
    EMER_H_axis:0,
    klm_kruis12_lvl_axis:0,
    klm_kruis12_current_axis:0,
    klm_kruis12_bar_axis:0,
    klm_kruis12_flow_rate_axis:0,
    klm_kruis12_total_flow_axis:0,
    klm_kruis13_lvl_axis:0,
    klm_kruis13_current_axis:0,
    klm_kruis13_bar_axis:0,
    klm_kruis13_flow_rate_axis:0,
    klm_kruis13_total_flow_axis:0,
    klm_kruis14_lvl_axis:0,
    klm_kruis14_current_axis:0,
    klm_kruis14_bar_axis:0,
    klm_kruis14_flow_rate_axis:0,
    klm_kruis14_total_flow_axis:0,
    klm_hup_wtw_flow_axis:0,
    klm_hup_wtw_tf_axis:0,
    klm_kruis_res_lvl_axis:0,
    isuzu_oven1_vsd_speed_axis:0,
isuzu_oven1_heat_ecvh_temp_axis:0,
isuzu_oven1_temp1_axis:0,
isuzu_oven1_temp2_axis:0,
isuzu_oven2_vsd_speed_axis:0,
isuzu_oven2_heat_ecvh_temp_axis:0,
isuzu_oven2_temp1_axis:0,
isuzu_oven2_temp2_axis:0,
WDNR_ROSE_TF_axis:0,
WDNR_ROSE_FR_axis:0,
WDSR_ROWP_BAR_axis:0,
WDSR_ROWP_TF_axis:0,
WDSR_ROWP_FR_axis:0,

lint_wtw_back_wash_FR_Axis:0,
lint_wtw_back_wash_TF_Axis:0,
lint_wtw_raw_water_FR_Axis:0,
lint_wtw_raw_water_TF_Axis:0,
lint_wtw_final_water_FR_Axis:0,
lint_wtw_final_water_TF_Axis:0,
lint_res_lvl_Axis:0,

  }


export const variables:any = {
  glen_FTP_WTW_P1_rtm_arr:[],
glen_FTP_WTW_P2_rtm_arr:[],
glen_FTP_WTW_P1_stn_arr:[],
glen_FTP_WTW_P2_stn_arr:[],
glen_FTP_WTW_ph_arr:[],
glen_FTP_WTW_orp_arr:[],
hank_ps_g_total_flow_1_arr:[],
hank_ps_g_total_flow_2_arr:[],
hank_ps_g_sump_level_arr:[],
hank_ps_g_flow_rate_1_arr:[],
hank_ps_g_flow_rate_2_arr:[],
hank_ps_p1_speed_arr:[],
hank_ps_p2_speed_arr:[],
hank_ps_p3_speed_arr:[],
para_flow_rate_arr:[],
para_total_flow_arr:[],
para_st_flow_rate_arr:[],
para_st_total_flow_arr:[],
    BERGEN_RES_R_LVL_arr:[],
    WOLWAS_RES_R_LVL_arr:[],
    UMI_RES_R_LVL_arr:[],
    KROON_RES_R_LVL_arr:[],
    TINROOF_LVL_RES_LVL_arr:[],
    DAMCAMP_LVL_RES_LVL_arr:[],
    HOLDING_LVL_RES_LVL_arr:[],
    BUSH_CHURCH_SOCO_FR_arr:[],
    BUSH_CHURCH_STEEL_FR_arr:[],
    BUSH_CHURCH_SOCCO_BAR_arr:[],
    BUSH_CHURCH_STEEL_BAR_arr:[],
    BUSH_PUMP_FR_arr:[],
    BUSH_GW_COMB_FLOW_RATE_arr:[],
    BUSH_TANK_LVL_arr:[],
    BUSH_GW_TF_arr:[],
    BUSH_PUMP_TF_arr:[],
    BUSH_STEEL_TF_arr:[],
    BUSH_SOCO_TF_arr:[],
    HUM_OFF_TAKE_TF_arr:[],
    HUM_OFF_TAKE_BAR_arr:[],
    HUM_OFF_TAKE_BAT_arr:[],
    JEFF_OFF_TAKE_TF_arr:[],
    JEFF_OFF_TAKE_BAT_arr:[],
    KOU_MAIN_LINE_BAR_arr:[],
    KOU_MAIN_LINE_BAT_arr:[],
    ONS_PARA_TF_arr:[],
    ONS_PARA_BAT_arr:[],
    ST_FRAN_OFF_TF_arr:[],
    PARA_BEA_TF_arr:[],
    ST_FRAN_PARA_BEA_BAT_arr:[],
    GBW_ACT_BAR_arr:[],
    GBW_FLO_RAT_arr:[],
    OLI_LVL_array: [],
    CGK_PRESSURE_array:[],
    CGK_LEVEL_array:[],
    CGK_KOP_NC_17_ML_array:[],
    CGK_MOTHERWELL_FLOW_RATE_array:[],
    CGK_GRASSRIDGE_FLOW_RATE_array:[],
    CGK_COEGA_FLOW_RATE_array:[],
    CGK_MOTHERWELL_TOTAL_FLOW_array:[],
    CGK_GRASSRIDGE_TOTAL_FLOW_array:[],
    CGK_COEGA_TOTAL_FLOW_array:[],
    NMB_SCHOE_PRESSURE_array:[],
    NMB_SCHOE_RES_LEVEL_array:[],
    NMB_SCHOE_ACTUATOR_POSITION_array:[],
    NMB_SCHOE_ACTUATOR_SET_POINT_array:[],
    ELA_FR_arr:[],
    ELA_P_arr:[],
    EMER_H_Level_arr: [],
    AIR_PRT_LVL_arr:[],
    LSD_PRESSURE_arr:[],
    LSD_TOTAL_FLOW_arr:[],
    LSD_FLOW_RATE_arr:[],
    McNougTown_PRESSURE_arr:[],
    McNougTown_TOTAL_FLOW_arr:[],
    McNougTown_FLOW_RATE_arr:[],
    EMER_H_Total_Flow_arr: [],
    EMER_H_Flow_Rate_arr: [],
    drift_R_reservoir_level_arr: [],
    drift_R_flow_rate_1_arr: [],
    drift_R_flow_rate_2_arr: [],
     drift_R_total_flow_1_arr: [],
    drift_R_total_flow_2_arr: [],
    nmb_schoe_r_actuator_valve_feedback_signal_error_arr:[],
    nmb_schoe_r_actuator_valve_command_signal_error_arr:[],
    nmb_schoe_r_reservoir_level_signal_error_arr:[],
    nmb_schoe_r_actuator_valve_fault_arr:[],
    nmb_schoe_r_actuator_valve_torque_fail_close_arr:[],
    nmb_schoe_r_actuator_valve_torque_fail_open_arr:[],
    nmb_schoe_r_general_fault_arr:[],
    nmb_schoe_r_actuator_general_fault_arr:[],
    nmb_schoe_r_actuator_valve_timeout_arr:[],
    KARK_K1_TF_arr:[],
    glen_r_res_lvl_arr:[],
    glen_FTP_WTW_Inlet_Flow_Rate_arr:[],
    glen_FTP_WTW_Inlet_Total_Flow_arr:[],
    glen_FTP_WTW_Inlet_bar_arr:[],
    glen_FTP_WTW_borehole_Flow_Rate_arr:[],
    glen_FTP_WTW_borehole_Total_Flow_arr:[],
    KARK_K1_FR_arr:[],
    KARK_K1_CUR_arr:[],
    KARK_K1_LVL_arr:[],
    KARK_K2_TF_arr:[],
    KARK_K2_FR_arr:[],
    KARK_K2_CUR_arr:[],
    KARK_K2_LVL_arr:[],
    GBarray:[],
    GBFRarray:[],
    CHE_East_array:[],
    CHE_West_array:[],
    CHE_R_FR1200_arr:[],
    CHE_R_FR600_arr:[],
    CHE_R_TF1200_arr:[],
    CHE_R_TF600_arr:[],
    CHE_FlowRate_array:[],
    GR_EC_array:[],
    GR_WC_array:[],
    VSarray:[],
    CHT_NC_array:[],
    CHT_OR_array:[],
    CHT_SC_array:[],
    VRH_DL_array:[],
    VRH_SL_array:[],
    HBarray:[],
    hb_P1_CURRENT_arr:[],
    hb_P2_CURRENT_arr:[],
    hb_P3_CURRENT_arr:[],
    hb_P1_RH_arr:[],
    hb_P2_RH_arr:[],
    hb_P3_RH_arr:[],
    LHarray:[],
    DRS_LH_RES_LVL_arr:[],
    BHB_array:[],
    TCarray:[],
    RD_LVL_array:[],
    SM_LVL_array:[],
    SM_FR_array:[],
    FMT_PRESS_array:[],
    FMT_FR_array:[],
    FMT_TF_array:[],
    IDZ_FR_array:[],
    IDZ_MW_FR_array:[],
    GT_BRG_STL_FR_array:[],
    GT_BRG_SOCO_FR_array:[],
    GT_BRG_STL_PRESS_array:[],
    GT_BRG_SOCO_PRESS_array:[],
    UIT_FC_FR_array:[],
    UIT_FC_PRESS_array:[],
    BETH_PRESS_array:[],
    BETH_FLOW_RATE_array:[],
    BETH_BATTERY_STATUS_array: [],
    BETH_TOTAL_FLOW_array: [],
    CG_CSP_Arr: [],
    CG_CDP_Arr: [],
    CG_S_LVL_Arr: [],
    CG_T1_LVL_Arr: [],
    CG_T1_IF_Arr: [],
    CG_T1_OF_Arr: [],
    CG_T2_LVL_Arr: [],
    CG_T2_IF_Arr: [],
    CG_T2_OF_Arr: [],
    NMU_EFF_FR_Arr: [],
    NMU_EFF_DP_Arr: [],
    NMU_EFF_DAM_LVL_Arr: [],
    NMU_EFF_P1_SPEED_Arr: [],
    NMU_EFF_P2_SPEED_Arr: [],
    NMU_EFF_P3_SPEED_Arr: [],
    NMU_EFF_JP_SPEED_Arr: [],
    CHE_PS_P1_ACTUAL_SPEED_Arr: [],
    CHE_PS_P1_DEL_PRESS_Arr: [],
    CHE_PS_P1_SUCT_PRESS_Arr: [],
    CHE_PS_P2_ACTUAL_SPEED_Arr: [],
    CHE_PS_P2_DEL_PRESS_Arr: [],
    CHE_PS_P2_SUCT_PRESS_Arr: [],
    CHE_PS_P3_ACTUAL_SPEED_Arr: [],
    CHE_PS_P3_DEL_PRESS_Arr: [],
    CHE_PS_P3_SUCT_PRESS_Arr: [],
    CHE_PS_P4_ACTUAL_SPEED_Arr: [],
    CHE_PS_P4_DEL_PRESS_Arr: [],
    CHE_PS_P4_SUCT_PRESS_Arr: [],
    CHE_PS_700_FLOW_RATE_Arr:[],
    CHE_PS_700_TOTAL_FLOW_Arr:[],
    NMBM_NPP_GW_PRESSURE_Arr:[],
    NMBM_NPP_GW_FLOW_RATE_Arr:[],
    NMBM_NPP_GW_LEVEL_Arr:[],
    NMBM_NPP_GW_TOTAL_FLOW_Arr:[],
    KLM_HUP_WATER_LEVEL_Arr:[],
    KLM_HUP_FLOWRATE_Arr:[],
    KLM_HUP_TOTALFLOW_Arr:[],
    KLM_HUP2_WATER_LEVEL_Arr:[],
    KLM_HUP2_FLOWRATE_Arr:[],
    KLM_HUP2_TOTALFLOW_Arr:[],
    KLM_HUP3_WATER_LEVEL_Arr:[],
    KLM_HUP3_FLOWRATE_Arr:[],
    KLM_HUP3_TOTALFLOW_Arr:[],
    KLM_HUP4_WATER_LEVEL_Arr:[],
    KLM_HUP4_FLOWRATE_Arr:[],
    KLM_HUP4_TOTALFLOW_Arr:[],
    KLM_HUP6_WATER_LEVEL_Arr:[],
    KLM_HUP6_FLOWRATE_Arr:[],
    KLM_HUP6_TOTALFLOW_Arr:[],
    STORMS_QUARRY_LEVEL_Arr:[],
    STORMS_GORGE_LEVEL_Arr:[],
    STORMS_HOLDING_RESERVOIR_LEVEL_Arr:[],
    STORMS_OVERHEAD_TANK_LEVEL_Arr:[],
    STAN_BPS_SuctionPressure_Arr: [],
    STAN_BPS_DeliveryPressure_Arr: [],
    STAN_BPS_FlowRate_Arr: [],
    STAN_BPS_P1_FREQ_Arr: [],
    STAN_BPS_P2_FREQ_Arr: [],
    STAN_BPS_P3_FREQ_Arr: [],
    STAN_BPS_P4_FREQ_Arr: [],
    MW_BPS_FlowRate_Arr: [],
    MW_BPS_SuctionPressure_Arr: [],
    MW_BPS_DeliveryPressure_Arr: [],
    MW_NORTH_LVL_array:[],
    MW_SOUTH_LVL_array:[],

    MW_P_TF_arr:[],
MW_P1_PUMP_RPM_arr:[],
MW_P2_PUMP_RPM_arr:[],
MW_P3_PUMP_RPM_arr:[],
MW_P4_PUMP_RPM_arr:[],
    WTW_NGT_FM_HIGH_FR_Arr: [],
    WTW_NGT_FM_LOW_FR_Arr: [],
    GR_R_INLET_Arr:[],
    GR_R_OUTLET_Arr:[],
    HUM_GW_BOR_LVL_arr: [],
    HUM_GW_RAW_WATER_TANK_LVL_arr: [],
    HUM_GW_FIN_WAT_TANK_LVL_arr: [],
    st_georges_wtw_gw_FR_arr: [],
    st_georges_wtw_gw_TF_arr:[],
    st_georges_wtw_emer_hill_FR_arr:[],
    st_georges_wtw_emer_hill_TF_arr:[],
    mala_lvl_arr:[],
    klm_kruis12_lvl_arr:[],
    klm_kruis12_current_arr:[],
    klm_kruis12_bar_arr:[],
    klm_kruis12_flow_rate_arr:[],
    klm_kruis12_total_flow_arr:[],
    klm_kruis13_lvl_arr:[],
    klm_kruis13_current_arr:[],
    klm_kruis13_bar_arr:[],
    klm_kruis13_flow_rate_arr:[],
    klm_kruis13_total_flow_arr:[],
    klm_kruis14_lvl_arr:[],
    klm_kruis14_current_arr:[],
    klm_kruis14_bar_arr:[],
    klm_kruis14_flow_rate_arr:[],
    klm_kruis14_total_flow_arr:[],
    klm_hup_wtw_flow_arr:[],
    klm_hup_wtw_tf_arr:[],
    klm_kruis_res_lvl_arr:[],
    KWANO_R_RES_LVL_arr:[],
    KWANO_R_FLOW_RATE_1_arr:[],
    KWANO_R_FLOW_RATE_2_arr:[],
    KWANO_R_TOTAL_FLOW_1_arr:[],
    KWANO_R_TOTAL_FLOW_2_arr:[],
    isuzu_oven1_vsd_speed_arr:[],
    isuzu_oven1_heat_ecvh_temp_arr:[],
    isuzu_oven1_temp1_arr:[],
    isuzu_oven1_temp2_arr:[],
    isuzu_oven2_vsd_speed_arr:[],
    isuzu_oven2_heat_ecvh_temp_arr:[],
    isuzu_oven2_temp1_arr:[],
    isuzu_oven2_temp2_arr:[],
    WDNR_ROSE_TF_arr:[],
    WDNR_ROSE_FR_arr:[],
    WDSR_ROWP_BAR_arr:[],
    WDSR_ROWP_TF_arr:[],
    WDSR_ROWP_FR_arr:[],
    lint_wtw_back_wash_FR_ARR:[],
    lint_wtw_back_wash_TF_ARR:[],
    lint_wtw_raw_water_FR_ARR:[],
    lint_wtw_raw_water_TF_ARR:[],
    lint_wtw_final_water_FR_ARR:[],
    lint_wtw_final_water_TF_ARR:[],
    lint_res_lvl_ARR:[],
  }





export class TrendPicker {
  dataSource:any;
  ELEMENT_DATA: PeriodicElement[] = [];
  displayedColumns :string[]= ['name','min', 'max', 'average'];
  SitesList: string[] = [];

  filterValue: any="";

public static getArray(route:any, array:any)
{

  for(let i = 0; i < array.length; i++){
    [array[i]] = route[0][array[i]]

  }

  return[array]


}




public createReservoirLevelSeries(name: string, data: any, yAxisIndex: number) {
  return {
    name,
    type: 'line',
    showSymbol: false,
    hoverAnimation: true,
    data,
    smooth: true,
    yAxisIndex,
  };
}

public static getRouteDataForTrendPicker(data:any, variable:any,tagArr:any){

    var trend :any;
    trend = data;

    for(var i = 0; i<trendArray.length; i++){
      variable[trendArray[i]] = trend[trendArray[i]];
    }


    return  variable;

    }

  }
